package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "amazon" operation group.
 * Reach it via {@code client.amazon()}.
 */
public final class AmazonGroup {
    private final CrawloraClient client;

    public AmazonGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * amazon-product (GET /amazon/product/{asin}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object product(Map<String, Object> params) {
        return product(params, null);
    }

    /**
     * amazon-product (GET /amazon/product/{asin}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object product(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("amazon-product", params);
        return client.request("amazon-product", params, options);
    }

    /**
     * amazon-search (GET /amazon/search).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object search(Map<String, Object> params) {
        return search(params, null);
    }

    /**
     * amazon-search (GET /amazon/search). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object search(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("amazon-search", params);
        return client.request("amazon-search", params, options);
    }

    /**
     * amazon-suggest (GET /amazon/suggest/{keyword}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object suggest(Map<String, Object> params) {
        return suggest(params, null);
    }

    /**
     * amazon-suggest (GET /amazon/suggest/{keyword}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object suggest(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("amazon-suggest", params);
        return client.request("amazon-suggest", params, options);
    }

}
