package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "appleBooks" operation group.
 * Reach it via {@code client.appleBooks()}.
 */
public final class AppleBooksGroup {
    private final CrawloraClient client;

    public AppleBooksGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * apple-books-audiobook-series (GET /apple-books/audiobook-series/{id}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object audiobookSeries(Map<String, Object> params) {
        return audiobookSeries(params, null);
    }

    /**
     * apple-books-audiobook-series (GET /apple-books/audiobook-series/{id}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object audiobookSeries(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("apple-books-audiobook-series", params);
        return client.request("apple-books-audiobook-series", params, options);
    }

    /**
     * apple-books-audiobook-search (GET /apple-books/audiobook/search).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object audiobookSearch(Map<String, Object> params) {
        return audiobookSearch(params, null);
    }

    /**
     * apple-books-audiobook-search (GET /apple-books/audiobook/search). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object audiobookSearch(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("apple-books-audiobook-search", params);
        return client.request("apple-books-audiobook-search", params, options);
    }

    /**
     * apple-books-audiobook (GET /apple-books/audiobook/{id}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object audiobook(Map<String, Object> params) {
        return audiobook(params, null);
    }

    /**
     * apple-books-audiobook (GET /apple-books/audiobook/{id}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object audiobook(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("apple-books-audiobook", params);
        return client.request("apple-books-audiobook", params, options);
    }

    /**
     * apple-books-audiobook-reviews (GET /apple-books/audiobook/{id}/reviews).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object audiobookReviews(Map<String, Object> params) {
        return audiobookReviews(params, null);
    }

    /**
     * apple-books-audiobook-reviews (GET /apple-books/audiobook/{id}/reviews). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object audiobookReviews(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("apple-books-audiobook-reviews", params);
        return client.request("apple-books-audiobook-reviews", params, options);
    }

    /**
     * apple-books-audiobook-similar (GET /apple-books/audiobook/{id}/similar).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object audiobookSimilar(Map<String, Object> params) {
        return audiobookSimilar(params, null);
    }

    /**
     * apple-books-audiobook-similar (GET /apple-books/audiobook/{id}/similar). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object audiobookSimilar(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("apple-books-audiobook-similar", params);
        return client.request("apple-books-audiobook-similar", params, options);
    }

    /**
     * apple-books-author (GET /apple-books/author/{id}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object author(Map<String, Object> params) {
        return author(params, null);
    }

    /**
     * apple-books-author (GET /apple-books/author/{id}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object author(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("apple-books-author", params);
        return client.request("apple-books-author", params, options);
    }

    /**
     * apple-books-book (GET /apple-books/book/{id}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object book(Map<String, Object> params) {
        return book(params, null);
    }

    /**
     * apple-books-book (GET /apple-books/book/{id}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object book(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("apple-books-book", params);
        return client.request("apple-books-book", params, options);
    }

    /**
     * apple-books-book-reviews (GET /apple-books/book/{id}/reviews).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object bookReviews(Map<String, Object> params) {
        return bookReviews(params, null);
    }

    /**
     * apple-books-book-reviews (GET /apple-books/book/{id}/reviews). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object bookReviews(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("apple-books-book-reviews", params);
        return client.request("apple-books-book-reviews", params, options);
    }

    /**
     * apple-books-book-similar (GET /apple-books/book/{id}/similar).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object bookSimilar(Map<String, Object> params) {
        return bookSimilar(params, null);
    }

    /**
     * apple-books-book-similar (GET /apple-books/book/{id}/similar). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object bookSimilar(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("apple-books-book-similar", params);
        return client.request("apple-books-book-similar", params, options);
    }

    /**
     * apple-books-charts (GET /apple-books/charts).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object charts(Map<String, Object> params) {
        return charts(params, null);
    }

    /**
     * apple-books-charts (GET /apple-books/charts). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object charts(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("apple-books-charts", params);
        return client.request("apple-books-charts", params, options);
    }

    /**
     * apple-books-charts (GET /apple-books/charts). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object charts() {
        return charts(Map.of(), null);
    }

    /**
     * apple-books-search (GET /apple-books/search).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object search(Map<String, Object> params) {
        return search(params, null);
    }

    /**
     * apple-books-search (GET /apple-books/search). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object search(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("apple-books-search", params);
        return client.request("apple-books-search", params, options);
    }

    /**
     * apple-books-series (GET /apple-books/series/{id}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object series(Map<String, Object> params) {
        return series(params, null);
    }

    /**
     * apple-books-series (GET /apple-books/series/{id}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object series(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("apple-books-series", params);
        return client.request("apple-books-series", params, options);
    }

}
