package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "bilibili" operation group.
 * Reach it via {@code client.bilibili()}.
 */
public final class BilibiliGroup {
    private final CrawloraClient client;

    public BilibiliGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * bilibili-anime-home (GET /bilibili/anime-home).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object animeHome(Map<String, Object> params) {
        return animeHome(params, null);
    }

    /**
     * bilibili-anime-home (GET /bilibili/anime-home). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object animeHome(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("bilibili-anime-home", params);
        return client.request("bilibili-anime-home", params, options);
    }

    /**
     * bilibili-anime-home (GET /bilibili/anime-home). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object animeHome() {
        return animeHome(Map.of(), null);
    }

    /**
     * bilibili-autocomplete (GET /bilibili/autocomplete).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object autocomplete(Map<String, Object> params) {
        return autocomplete(params, null);
    }

    /**
     * bilibili-autocomplete (GET /bilibili/autocomplete). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object autocomplete(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("bilibili-autocomplete", params);
        return client.request("bilibili-autocomplete", params, options);
    }

    /**
     * bilibili-guochuang-home (GET /bilibili/guochuang-home).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object guochuangHome(Map<String, Object> params) {
        return guochuangHome(params, null);
    }

    /**
     * bilibili-guochuang-home (GET /bilibili/guochuang-home). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object guochuangHome(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("bilibili-guochuang-home", params);
        return client.request("bilibili-guochuang-home", params, options);
    }

    /**
     * bilibili-guochuang-home (GET /bilibili/guochuang-home). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object guochuangHome() {
        return guochuangHome(Map.of(), null);
    }

    /**
     * bilibili-must-watch (GET /bilibili/must-watch).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object mustWatch(Map<String, Object> params) {
        return mustWatch(params, null);
    }

    /**
     * bilibili-must-watch (GET /bilibili/must-watch). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object mustWatch(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("bilibili-must-watch", params);
        return client.request("bilibili-must-watch", params, options);
    }

    /**
     * bilibili-must-watch (GET /bilibili/must-watch). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object mustWatch() {
        return mustWatch(Map.of(), null);
    }

    /**
     * bilibili-popular (GET /bilibili/popular).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object popular(Map<String, Object> params) {
        return popular(params, null);
    }

    /**
     * bilibili-popular (GET /bilibili/popular). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object popular(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("bilibili-popular", params);
        return client.request("bilibili-popular", params, options);
    }

    /**
     * bilibili-popular (GET /bilibili/popular). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object popular() {
        return popular(Map.of(), null);
    }

    /**
     * bilibili-ranking (GET /bilibili/ranking).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object ranking(Map<String, Object> params) {
        return ranking(params, null);
    }

    /**
     * bilibili-ranking (GET /bilibili/ranking). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object ranking(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("bilibili-ranking", params);
        return client.request("bilibili-ranking", params, options);
    }

    /**
     * bilibili-ranking (GET /bilibili/ranking). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object ranking() {
        return ranking(Map.of(), null);
    }

    /**
     * bilibili-vertical-home (GET /bilibili/vertical-home).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object verticalHome(Map<String, Object> params) {
        return verticalHome(params, null);
    }

    /**
     * bilibili-vertical-home (GET /bilibili/vertical-home). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object verticalHome(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("bilibili-vertical-home", params);
        return client.request("bilibili-vertical-home", params, options);
    }

    /**
     * bilibili-weekly (GET /bilibili/weekly).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object weekly(Map<String, Object> params) {
        return weekly(params, null);
    }

    /**
     * bilibili-weekly (GET /bilibili/weekly). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object weekly(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("bilibili-weekly", params);
        return client.request("bilibili-weekly", params, options);
    }

    /**
     * bilibili-weekly (GET /bilibili/weekly). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object weekly() {
        return weekly(Map.of(), null);
    }

}
