package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "bleacherReport" operation group.
 * Reach it via {@code client.bleacherReport()}.
 */
public final class BleacherReportGroup {
    private final CrawloraClient client;

    public BleacherReportGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * bleacherreport-article (GET /bleacherreport/article).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object bleacherreportArticle(Map<String, Object> params) {
        return bleacherreportArticle(params, null);
    }

    /**
     * bleacherreport-article (GET /bleacherreport/article). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object bleacherreportArticle(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("bleacherreport-article", params);
        return client.request("bleacherreport-article", params, options);
    }

    /**
     * bleacherreport-author (GET /bleacherreport/author).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object bleacherreportAuthor(Map<String, Object> params) {
        return bleacherreportAuthor(params, null);
    }

    /**
     * bleacherreport-author (GET /bleacherreport/author). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object bleacherreportAuthor(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("bleacherreport-author", params);
        return client.request("bleacherreport-author", params, options);
    }

    /**
     * bleacherreport-author (GET /bleacherreport/author). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object bleacherreportAuthor() {
        return bleacherreportAuthor(Map.of(), null);
    }

    /**
     * bleacherreport-headlines (GET /bleacherreport/headlines).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object bleacherreportHeadlines(Map<String, Object> params) {
        return bleacherreportHeadlines(params, null);
    }

    /**
     * bleacherreport-headlines (GET /bleacherreport/headlines). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object bleacherreportHeadlines(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("bleacherreport-headlines", params);
        return client.request("bleacherreport-headlines", params, options);
    }

    /**
     * bleacherreport-news (GET /bleacherreport/news).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object bleacherreportNews(Map<String, Object> params) {
        return bleacherreportNews(params, null);
    }

    /**
     * bleacherreport-news (GET /bleacherreport/news). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object bleacherreportNews(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("bleacherreport-news", params);
        return client.request("bleacherreport-news", params, options);
    }

    /**
     * bleacherreport-news (GET /bleacherreport/news). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object bleacherreportNews() {
        return bleacherreportNews(Map.of(), null);
    }

    /**
     * bleacherreport-sections (GET /bleacherreport/sections).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object bleacherreportSections(Map<String, Object> params) {
        return bleacherreportSections(params, null);
    }

    /**
     * bleacherreport-sections (GET /bleacherreport/sections). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object bleacherreportSections(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("bleacherreport-sections", params);
        return client.request("bleacherreport-sections", params, options);
    }

    /**
     * bleacherreport-sections (GET /bleacherreport/sections). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object bleacherreportSections() {
        return bleacherreportSections(Map.of(), null);
    }

}
