package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "burberry" operation group.
 * Reach it via {@code client.burberry()}.
 */
public final class BurberryGroup {
    private final CrawloraClient client;

    public BurberryGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * burberry-categories (GET /burberry/categories).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object categories(Map<String, Object> params) {
        return categories(params, null);
    }

    /**
     * burberry-categories (GET /burberry/categories). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object categories(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("burberry-categories", params);
        return client.request("burberry-categories", params, options);
    }

    /**
     * burberry-categories (GET /burberry/categories). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object categories() {
        return categories(Map.of(), null);
    }

    /**
     * burberry-category (GET /burberry/category).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object category(Map<String, Object> params) {
        return category(params, null);
    }

    /**
     * burberry-category (GET /burberry/category). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object category(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("burberry-category", params);
        return client.request("burberry-category", params, options);
    }

    /**
     * burberry-product (GET /burberry/product).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object product(Map<String, Object> params) {
        return product(params, null);
    }

    /**
     * burberry-product (GET /burberry/product). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object product(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("burberry-product", params);
        return client.request("burberry-product", params, options);
    }

    /**
     * burberry-related (GET /burberry/related).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object related(Map<String, Object> params) {
        return related(params, null);
    }

    /**
     * burberry-related (GET /burberry/related). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object related(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("burberry-related", params);
        return client.request("burberry-related", params, options);
    }

    /**
     * burberry-search (GET /burberry/search).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object search(Map<String, Object> params) {
        return search(params, null);
    }

    /**
     * burberry-search (GET /burberry/search). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object search(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("burberry-search", params);
        return client.request("burberry-search", params, options);
    }

    /**
     * burberry-suggest (GET /burberry/suggest).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object suggest(Map<String, Object> params) {
        return suggest(params, null);
    }

    /**
     * burberry-suggest (GET /burberry/suggest). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object suggest(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("burberry-suggest", params);
        return client.request("burberry-suggest", params, options);
    }

}
