package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "carMax" operation group.
 * Reach it via {@code client.carMax()}.
 */
public final class CarMaxGroup {
    private final CrawloraClient client;

    public CarMaxGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * carmax-search (GET /carmax/search).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object carmaxSearch(Map<String, Object> params) {
        return carmaxSearch(params, null);
    }

    /**
     * carmax-search (GET /carmax/search). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object carmaxSearch(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("carmax-search", params);
        return client.request("carmax-search", params, options);
    }

    /**
     * carmax-search (GET /carmax/search). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object carmaxSearch() {
        return carmaxSearch(Map.of(), null);
    }

    /**
     * carmax-search-suggestions (GET /carmax/search/suggestions).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object carmaxSearchSuggestions(Map<String, Object> params) {
        return carmaxSearchSuggestions(params, null);
    }

    /**
     * carmax-search-suggestions (GET /carmax/search/suggestions). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object carmaxSearchSuggestions(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("carmax-search-suggestions", params);
        return client.request("carmax-search-suggestions", params, options);
    }

    /**
     * carmax-shop-by-brand (GET /carmax/shop-by-brand).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object carmaxShopByBrand(Map<String, Object> params) {
        return carmaxShopByBrand(params, null);
    }

    /**
     * carmax-shop-by-brand (GET /carmax/shop-by-brand). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object carmaxShopByBrand(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("carmax-shop-by-brand", params);
        return client.request("carmax-shop-by-brand", params, options);
    }

    /**
     * carmax-shop-by-brand (GET /carmax/shop-by-brand). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object carmaxShopByBrand() {
        return carmaxShopByBrand(Map.of(), null);
    }

    /**
     * carmax-store (GET /carmax/store/{id}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object carmaxStore(Map<String, Object> params) {
        return carmaxStore(params, null);
    }

    /**
     * carmax-store (GET /carmax/store/{id}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object carmaxStore(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("carmax-store", params);
        return client.request("carmax-store", params, options);
    }

    /**
     * carmax-stores (GET /carmax/stores).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object carmaxStores(Map<String, Object> params) {
        return carmaxStores(params, null);
    }

    /**
     * carmax-stores (GET /carmax/stores). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object carmaxStores(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("carmax-stores", params);
        return client.request("carmax-stores", params, options);
    }

    /**
     * carmax-stores (GET /carmax/stores). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object carmaxStores() {
        return carmaxStores(Map.of(), null);
    }

    /**
     * carmax-vehicle (GET /carmax/vehicle/{stock_number}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object carmaxVehicle(Map<String, Object> params) {
        return carmaxVehicle(params, null);
    }

    /**
     * carmax-vehicle (GET /carmax/vehicle/{stock_number}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object carmaxVehicle(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("carmax-vehicle", params);
        return client.request("carmax-vehicle", params, options);
    }

    /**
     * carmax-vehicle-recommendations (GET /carmax/vehicle/{stock_number}/recommendations).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object carmaxVehicleRecommendations(Map<String, Object> params) {
        return carmaxVehicleRecommendations(params, null);
    }

    /**
     * carmax-vehicle-recommendations (GET /carmax/vehicle/{stock_number}/recommendations). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object carmaxVehicleRecommendations(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("carmax-vehicle-recommendations", params);
        return client.request("carmax-vehicle-recommendations", params, options);
    }

}
