package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "clevelandCom" operation group.
 * Reach it via {@code client.clevelandCom()}.
 */
public final class ClevelandComGroup {
    private final CrawloraClient client;

    public ClevelandComGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * clevelandcom-news (GET /clevelandcom/news).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object clevelandcomNews(Map<String, Object> params) {
        return clevelandcomNews(params, null);
    }

    /**
     * clevelandcom-news (GET /clevelandcom/news). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object clevelandcomNews(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("clevelandcom-news", params);
        return client.request("clevelandcom-news", params, options);
    }

    /**
     * clevelandcom-news (GET /clevelandcom/news). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object clevelandcomNews() {
        return clevelandcomNews(Map.of(), null);
    }

}
