package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "cnn" operation group.
 * Reach it via {@code client.cnn()}.
 */
public final class CnnGroup {
    private final CrawloraClient client;

    public CnnGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * cnn-article (GET /cnn/article).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object article(Map<String, Object> params) {
        return article(params, null);
    }

    /**
     * cnn-article (GET /cnn/article). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object article(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("cnn-article", params);
        return client.request("cnn-article", params, options);
    }

    /**
     * cnn-headlines (GET /cnn/headlines).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object headlines(Map<String, Object> params) {
        return headlines(params, null);
    }

    /**
     * cnn-headlines (GET /cnn/headlines). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object headlines(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("cnn-headlines", params);
        return client.request("cnn-headlines", params, options);
    }

    /**
     * cnn-headlines (GET /cnn/headlines). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object headlines() {
        return headlines(Map.of(), null);
    }

    /**
     * cnn-live-story (GET /cnn/live-story).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object liveStory(Map<String, Object> params) {
        return liveStory(params, null);
    }

    /**
     * cnn-live-story (GET /cnn/live-story). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object liveStory(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("cnn-live-story", params);
        return client.request("cnn-live-story", params, options);
    }

}
