package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "dominos" operation group.
 * Reach it via {@code client.dominos()}.
 */
public final class DominosGroup {
    private final CrawloraClient client;

    public DominosGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * dominos-coupons (GET /dominos/coupons).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object coupons(Map<String, Object> params) {
        return coupons(params, null);
    }

    /**
     * dominos-coupons (GET /dominos/coupons). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object coupons(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("dominos-coupons", params);
        return client.request("dominos-coupons", params, options);
    }

    /**
     * dominos-customization (GET /dominos/customization).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object customization(Map<String, Object> params) {
        return customization(params, null);
    }

    /**
     * dominos-customization (GET /dominos/customization). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object customization(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("dominos-customization", params);
        return client.request("dominos-customization", params, options);
    }

    /**
     * dominos-menu (GET /dominos/menu).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object menu(Map<String, Object> params) {
        return menu(params, null);
    }

    /**
     * dominos-menu (GET /dominos/menu). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object menu(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("dominos-menu", params);
        return client.request("dominos-menu", params, options);
    }

    /**
     * dominos-nutrition (GET /dominos/nutrition).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object nutrition(Map<String, Object> params) {
        return nutrition(params, null);
    }

    /**
     * dominos-nutrition (GET /dominos/nutrition). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object nutrition(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("dominos-nutrition", params);
        return client.request("dominos-nutrition", params, options);
    }

    /**
     * dominos-store (GET /dominos/store).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object store(Map<String, Object> params) {
        return store(params, null);
    }

    /**
     * dominos-store (GET /dominos/store). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object store(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("dominos-store", params);
        return client.request("dominos-store", params, options);
    }

    /**
     * dominos-store-locator (GET /dominos/store-locator).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object storeLocator(Map<String, Object> params) {
        return storeLocator(params, null);
    }

    /**
     * dominos-store-locator (GET /dominos/store-locator). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object storeLocator(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("dominos-store-locator", params);
        return client.request("dominos-store-locator", params, options);
    }

    /**
     * dominos-store-locator (GET /dominos/store-locator). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object storeLocator() {
        return storeLocator(Map.of(), null);
    }

}
