package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "etsy" operation group.
 * Reach it via {@code client.etsy()}.
 */
public final class EtsyGroup {
    private final CrawloraClient client;

    public EtsyGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * etsy-listing (GET /etsy/listing/{id}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object listing(Map<String, Object> params) {
        return listing(params, null);
    }

    /**
     * etsy-listing (GET /etsy/listing/{id}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object listing(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("etsy-listing", params);
        return client.request("etsy-listing", params, options);
    }

    /**
     * etsy-listing-reviews (GET /etsy/listing/{id}/reviews).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object listingReviews(Map<String, Object> params) {
        return listingReviews(params, null);
    }

    /**
     * etsy-listing-reviews (GET /etsy/listing/{id}/reviews). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object listingReviews(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("etsy-listing-reviews", params);
        return client.request("etsy-listing-reviews", params, options);
    }

    /**
     * etsy-search (GET /etsy/search).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object search(Map<String, Object> params) {
        return search(params, null);
    }

    /**
     * etsy-search (GET /etsy/search). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object search(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("etsy-search", params);
        return client.request("etsy-search", params, options);
    }

    /**
     * etsy-shop-search (GET /etsy/shop/search).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object shopSearch(Map<String, Object> params) {
        return shopSearch(params, null);
    }

    /**
     * etsy-shop-search (GET /etsy/shop/search). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object shopSearch(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("etsy-shop-search", params);
        return client.request("etsy-shop-search", params, options);
    }

    /**
     * etsy-shop (GET /etsy/shop/{id}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object shop(Map<String, Object> params) {
        return shop(params, null);
    }

    /**
     * etsy-shop (GET /etsy/shop/{id}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object shop(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("etsy-shop", params);
        return client.request("etsy-shop", params, options);
    }

    /**
     * etsy-shop-listings (GET /etsy/shop/{id}/listings).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object shopListings(Map<String, Object> params) {
        return shopListings(params, null);
    }

    /**
     * etsy-shop-listings (GET /etsy/shop/{id}/listings). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object shopListings(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("etsy-shop-listings", params);
        return client.request("etsy-shop-listings", params, options);
    }

    /**
     * etsy-shop-reviews (GET /etsy/shop/{id}/reviews).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object shopReviews(Map<String, Object> params) {
        return shopReviews(params, null);
    }

    /**
     * etsy-shop-reviews (GET /etsy/shop/{id}/reviews). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object shopReviews(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("etsy-shop-reviews", params);
        return client.request("etsy-shop-reviews", params, options);
    }

}
