package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "eveningStandard" operation group.
 * Reach it via {@code client.eveningStandard()}.
 */
public final class EveningStandardGroup {
    private final CrawloraClient client;

    public EveningStandardGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * standard-article (GET /standard/article).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object standardArticle(Map<String, Object> params) {
        return standardArticle(params, null);
    }

    /**
     * standard-article (GET /standard/article). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object standardArticle(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("standard-article", params);
        return client.request("standard-article", params, options);
    }

    /**
     * standard-author (GET /standard/author).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object standardAuthor(Map<String, Object> params) {
        return standardAuthor(params, null);
    }

    /**
     * standard-author (GET /standard/author). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object standardAuthor(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("standard-author", params);
        return client.request("standard-author", params, options);
    }

    /**
     * standard-author (GET /standard/author). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object standardAuthor() {
        return standardAuthor(Map.of(), null);
    }

    /**
     * standard-headlines (GET /standard/headlines).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object standardHeadlines(Map<String, Object> params) {
        return standardHeadlines(params, null);
    }

    /**
     * standard-headlines (GET /standard/headlines). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object standardHeadlines(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("standard-headlines", params);
        return client.request("standard-headlines", params, options);
    }

    /**
     * standard-news (GET /standard/news).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object standardNews(Map<String, Object> params) {
        return standardNews(params, null);
    }

    /**
     * standard-news (GET /standard/news). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object standardNews(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("standard-news", params);
        return client.request("standard-news", params, options);
    }

    /**
     * standard-news (GET /standard/news). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object standardNews() {
        return standardNews(Map.of(), null);
    }

    /**
     * standard-sections (GET /standard/sections).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object standardSections(Map<String, Object> params) {
        return standardSections(params, null);
    }

    /**
     * standard-sections (GET /standard/sections). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object standardSections(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("standard-sections", params);
        return client.request("standard-sections", params, options);
    }

    /**
     * standard-sections (GET /standard/sections). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object standardSections() {
        return standardSections(Map.of(), null);
    }

}
