package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "freeMalaysiaToday" operation group.
 * Reach it via {@code client.freeMalaysiaToday()}.
 */
public final class FreeMalaysiaTodayGroup {
    private final CrawloraClient client;

    public FreeMalaysiaTodayGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * freemalaysiatoday-news (GET /freemalaysiatoday/news).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object freemalaysiatodayNews(Map<String, Object> params) {
        return freemalaysiatodayNews(params, null);
    }

    /**
     * freemalaysiatoday-news (GET /freemalaysiatoday/news). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object freemalaysiatodayNews(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("freemalaysiatoday-news", params);
        return client.request("freemalaysiatoday-news", params, options);
    }

    /**
     * freemalaysiatoday-news (GET /freemalaysiatoday/news). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object freemalaysiatodayNews() {
        return freemalaysiatodayNews(Map.of(), null);
    }

    /**
     * freemalaysiatoday-sections (GET /freemalaysiatoday/sections).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object freemalaysiatodaySections(Map<String, Object> params) {
        return freemalaysiatodaySections(params, null);
    }

    /**
     * freemalaysiatoday-sections (GET /freemalaysiatoday/sections). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object freemalaysiatodaySections(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("freemalaysiatoday-sections", params);
        return client.request("freemalaysiatoday-sections", params, options);
    }

    /**
     * freemalaysiatoday-sections (GET /freemalaysiatoday/sections). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object freemalaysiatodaySections() {
        return freemalaysiatodaySections(Map.of(), null);
    }

}
