package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "gitHub" operation group.
 * Reach it via {@code client.gitHub()}.
 */
public final class GitHubGroup {
    private final CrawloraClient client;

    public GitHubGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * github-org (GET /github/org/{org}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object githubOrg(Map<String, Object> params) {
        return githubOrg(params, null);
    }

    /**
     * github-org (GET /github/org/{org}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object githubOrg(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("github-org", params);
        return client.request("github-org", params, options);
    }

    /**
     * github-org-repos (GET /github/org/{org}/repos).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object githubOrgRepos(Map<String, Object> params) {
        return githubOrgRepos(params, null);
    }

    /**
     * github-org-repos (GET /github/org/{org}/repos). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object githubOrgRepos(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("github-org-repos", params);
        return client.request("github-org-repos", params, options);
    }

    /**
     * github-repo (GET /github/repo/{owner}/{repo}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object githubRepo(Map<String, Object> params) {
        return githubRepo(params, null);
    }

    /**
     * github-repo (GET /github/repo/{owner}/{repo}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object githubRepo(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("github-repo", params);
        return client.request("github-repo", params, options);
    }

    /**
     * github-repo-contributors (GET /github/repo/{owner}/{repo}/contributors).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object githubRepoContributors(Map<String, Object> params) {
        return githubRepoContributors(params, null);
    }

    /**
     * github-repo-contributors (GET /github/repo/{owner}/{repo}/contributors). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object githubRepoContributors(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("github-repo-contributors", params);
        return client.request("github-repo-contributors", params, options);
    }

    /**
     * github-repo-forks (GET /github/repo/{owner}/{repo}/forks).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object githubRepoForks(Map<String, Object> params) {
        return githubRepoForks(params, null);
    }

    /**
     * github-repo-forks (GET /github/repo/{owner}/{repo}/forks). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object githubRepoForks(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("github-repo-forks", params);
        return client.request("github-repo-forks", params, options);
    }

    /**
     * github-repo-languages (GET /github/repo/{owner}/{repo}/languages).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object githubRepoLanguages(Map<String, Object> params) {
        return githubRepoLanguages(params, null);
    }

    /**
     * github-repo-languages (GET /github/repo/{owner}/{repo}/languages). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object githubRepoLanguages(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("github-repo-languages", params);
        return client.request("github-repo-languages", params, options);
    }

    /**
     * github-repo-releases (GET /github/repo/{owner}/{repo}/releases).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object githubRepoReleases(Map<String, Object> params) {
        return githubRepoReleases(params, null);
    }

    /**
     * github-repo-releases (GET /github/repo/{owner}/{repo}/releases). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object githubRepoReleases(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("github-repo-releases", params);
        return client.request("github-repo-releases", params, options);
    }

    /**
     * github-repo-stargazers (GET /github/repo/{owner}/{repo}/stargazers).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object githubRepoStargazers(Map<String, Object> params) {
        return githubRepoStargazers(params, null);
    }

    /**
     * github-repo-stargazers (GET /github/repo/{owner}/{repo}/stargazers). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object githubRepoStargazers(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("github-repo-stargazers", params);
        return client.request("github-repo-stargazers", params, options);
    }

    /**
     * github-search-repositories (GET /github/search/repositories).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object githubSearchRepositories(Map<String, Object> params) {
        return githubSearchRepositories(params, null);
    }

    /**
     * github-search-repositories (GET /github/search/repositories). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object githubSearchRepositories(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("github-search-repositories", params);
        return client.request("github-search-repositories", params, options);
    }

    /**
     * github-search-users (GET /github/search/users).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object githubSearchUsers(Map<String, Object> params) {
        return githubSearchUsers(params, null);
    }

    /**
     * github-search-users (GET /github/search/users). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object githubSearchUsers(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("github-search-users", params);
        return client.request("github-search-users", params, options);
    }

    /**
     * github-trending (GET /github/trending).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object githubTrending(Map<String, Object> params) {
        return githubTrending(params, null);
    }

    /**
     * github-trending (GET /github/trending). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object githubTrending(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("github-trending", params);
        return client.request("github-trending", params, options);
    }

    /**
     * github-trending (GET /github/trending). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object githubTrending() {
        return githubTrending(Map.of(), null);
    }

    /**
     * github-trending-developers (GET /github/trending/developers).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object githubTrendingDevelopers(Map<String, Object> params) {
        return githubTrendingDevelopers(params, null);
    }

    /**
     * github-trending-developers (GET /github/trending/developers). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object githubTrendingDevelopers(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("github-trending-developers", params);
        return client.request("github-trending-developers", params, options);
    }

    /**
     * github-trending-developers (GET /github/trending/developers). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object githubTrendingDevelopers() {
        return githubTrendingDevelopers(Map.of(), null);
    }

    /**
     * github-user (GET /github/user/{username}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object githubUser(Map<String, Object> params) {
        return githubUser(params, null);
    }

    /**
     * github-user (GET /github/user/{username}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object githubUser(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("github-user", params);
        return client.request("github-user", params, options);
    }

    /**
     * github-user-events (GET /github/user/{username}/events).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object githubUserEvents(Map<String, Object> params) {
        return githubUserEvents(params, null);
    }

    /**
     * github-user-events (GET /github/user/{username}/events). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object githubUserEvents(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("github-user-events", params);
        return client.request("github-user-events", params, options);
    }

    /**
     * github-user-pinned (GET /github/user/{username}/pinned).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object githubUserPinned(Map<String, Object> params) {
        return githubUserPinned(params, null);
    }

    /**
     * github-user-pinned (GET /github/user/{username}/pinned). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object githubUserPinned(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("github-user-pinned", params);
        return client.request("github-user-pinned", params, options);
    }

    /**
     * github-user-repos (GET /github/user/{username}/repos).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object githubUserRepos(Map<String, Object> params) {
        return githubUserRepos(params, null);
    }

    /**
     * github-user-repos (GET /github/user/{username}/repos). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object githubUserRepos(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("github-user-repos", params);
        return client.request("github-user-repos", params, options);
    }

}
