package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "globeAndMail" operation group.
 * Reach it via {@code client.globeAndMail()}.
 */
public final class GlobeAndMailGroup {
    private final CrawloraClient client;

    public GlobeAndMailGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * globeandmail-article (GET /globeandmail/article).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object globeandmailArticle(Map<String, Object> params) {
        return globeandmailArticle(params, null);
    }

    /**
     * globeandmail-article (GET /globeandmail/article). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object globeandmailArticle(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("globeandmail-article", params);
        return client.request("globeandmail-article", params, options);
    }

    /**
     * globeandmail-author (GET /globeandmail/author).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object globeandmailAuthor(Map<String, Object> params) {
        return globeandmailAuthor(params, null);
    }

    /**
     * globeandmail-author (GET /globeandmail/author). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object globeandmailAuthor(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("globeandmail-author", params);
        return client.request("globeandmail-author", params, options);
    }

    /**
     * globeandmail-headlines (GET /globeandmail/headlines).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object globeandmailHeadlines(Map<String, Object> params) {
        return globeandmailHeadlines(params, null);
    }

    /**
     * globeandmail-headlines (GET /globeandmail/headlines). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object globeandmailHeadlines(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("globeandmail-headlines", params);
        return client.request("globeandmail-headlines", params, options);
    }

    /**
     * globeandmail-news (GET /globeandmail/news).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object globeandmailNews(Map<String, Object> params) {
        return globeandmailNews(params, null);
    }

    /**
     * globeandmail-news (GET /globeandmail/news). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object globeandmailNews(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("globeandmail-news", params);
        return client.request("globeandmail-news", params, options);
    }

    /**
     * globeandmail-news (GET /globeandmail/news). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object globeandmailNews() {
        return globeandmailNews(Map.of(), null);
    }

    /**
     * globeandmail-sections (GET /globeandmail/sections).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object globeandmailSections(Map<String, Object> params) {
        return globeandmailSections(params, null);
    }

    /**
     * globeandmail-sections (GET /globeandmail/sections). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object globeandmailSections(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("globeandmail-sections", params);
        return client.request("globeandmail-sections", params, options);
    }

    /**
     * globeandmail-sections (GET /globeandmail/sections). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object globeandmailSections() {
        return globeandmailSections(Map.of(), null);
    }

}
