package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "gulfNews" operation group.
 * Reach it via {@code client.gulfNews()}.
 */
public final class GulfNewsGroup {
    private final CrawloraClient client;

    public GulfNewsGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * gulfnews-article (GET /gulfnews/article).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object gulfnewsArticle(Map<String, Object> params) {
        return gulfnewsArticle(params, null);
    }

    /**
     * gulfnews-article (GET /gulfnews/article). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object gulfnewsArticle(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("gulfnews-article", params);
        return client.request("gulfnews-article", params, options);
    }

    /**
     * gulfnews-author (GET /gulfnews/author).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object gulfnewsAuthor(Map<String, Object> params) {
        return gulfnewsAuthor(params, null);
    }

    /**
     * gulfnews-author (GET /gulfnews/author). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object gulfnewsAuthor(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("gulfnews-author", params);
        return client.request("gulfnews-author", params, options);
    }

    /**
     * gulfnews-author (GET /gulfnews/author). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object gulfnewsAuthor() {
        return gulfnewsAuthor(Map.of(), null);
    }

    /**
     * gulfnews-headlines (GET /gulfnews/headlines).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object gulfnewsHeadlines(Map<String, Object> params) {
        return gulfnewsHeadlines(params, null);
    }

    /**
     * gulfnews-headlines (GET /gulfnews/headlines). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object gulfnewsHeadlines(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("gulfnews-headlines", params);
        return client.request("gulfnews-headlines", params, options);
    }

    /**
     * gulfnews-news (GET /gulfnews/news).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object gulfnewsNews(Map<String, Object> params) {
        return gulfnewsNews(params, null);
    }

    /**
     * gulfnews-news (GET /gulfnews/news). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object gulfnewsNews(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("gulfnews-news", params);
        return client.request("gulfnews-news", params, options);
    }

    /**
     * gulfnews-news (GET /gulfnews/news). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object gulfnewsNews() {
        return gulfnewsNews(Map.of(), null);
    }

    /**
     * gulfnews-sections (GET /gulfnews/sections).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object gulfnewsSections(Map<String, Object> params) {
        return gulfnewsSections(params, null);
    }

    /**
     * gulfnews-sections (GET /gulfnews/sections). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object gulfnewsSections(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("gulfnews-sections", params);
        return client.request("gulfnews-sections", params, options);
    }

    /**
     * gulfnews-sections (GET /gulfnews/sections). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object gulfnewsSections() {
        return gulfnewsSections(Map.of(), null);
    }

}
