package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "hindustanTimes" operation group.
 * Reach it via {@code client.hindustanTimes()}.
 */
public final class HindustanTimesGroup {
    private final CrawloraClient client;

    public HindustanTimesGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * hindustantimes-article (GET /hindustantimes/article).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object hindustantimesArticle(Map<String, Object> params) {
        return hindustantimesArticle(params, null);
    }

    /**
     * hindustantimes-article (GET /hindustantimes/article). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object hindustantimesArticle(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("hindustantimes-article", params);
        return client.request("hindustantimes-article", params, options);
    }

    /**
     * hindustantimes-author (GET /hindustantimes/author).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object hindustantimesAuthor(Map<String, Object> params) {
        return hindustantimesAuthor(params, null);
    }

    /**
     * hindustantimes-author (GET /hindustantimes/author). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object hindustantimesAuthor(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("hindustantimes-author", params);
        return client.request("hindustantimes-author", params, options);
    }

    /**
     * hindustantimes-headlines (GET /hindustantimes/headlines).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object hindustantimesHeadlines(Map<String, Object> params) {
        return hindustantimesHeadlines(params, null);
    }

    /**
     * hindustantimes-headlines (GET /hindustantimes/headlines). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object hindustantimesHeadlines(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("hindustantimes-headlines", params);
        return client.request("hindustantimes-headlines", params, options);
    }

    /**
     * hindustantimes-news (GET /hindustantimes/news).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object hindustantimesNews(Map<String, Object> params) {
        return hindustantimesNews(params, null);
    }

    /**
     * hindustantimes-news (GET /hindustantimes/news). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object hindustantimesNews(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("hindustantimes-news", params);
        return client.request("hindustantimes-news", params, options);
    }

    /**
     * hindustantimes-news (GET /hindustantimes/news). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object hindustantimesNews() {
        return hindustantimesNews(Map.of(), null);
    }

    /**
     * hindustantimes-sections (GET /hindustantimes/sections).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object hindustantimesSections(Map<String, Object> params) {
        return hindustantimesSections(params, null);
    }

    /**
     * hindustantimes-sections (GET /hindustantimes/sections). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object hindustantimesSections(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("hindustantimes-sections", params);
        return client.request("hindustantimes-sections", params, options);
    }

    /**
     * hindustantimes-sections (GET /hindustantimes/sections). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object hindustantimesSections() {
        return hindustantimesSections(Map.of(), null);
    }

}
