package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "ikea" operation group.
 * Reach it via {@code client.ikea()}.
 */
public final class IkeaGroup {
    private final CrawloraClient client;

    public IkeaGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * ikea-availability (GET /ikea/availability).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object availability(Map<String, Object> params) {
        return availability(params, null);
    }

    /**
     * ikea-availability (GET /ikea/availability). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object availability(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("ikea-availability", params);
        return client.request("ikea-availability", params, options);
    }

    /**
     * ikea-category (GET /ikea/category).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object category(Map<String, Object> params) {
        return category(params, null);
    }

    /**
     * ikea-category (GET /ikea/category). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object category(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("ikea-category", params);
        return client.request("ikea-category", params, options);
    }

    /**
     * ikea-product (GET /ikea/product).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object product(Map<String, Object> params) {
        return product(params, null);
    }

    /**
     * ikea-product (GET /ikea/product). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object product(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("ikea-product", params);
        return client.request("ikea-product", params, options);
    }

    /**
     * ikea-reviews (GET /ikea/reviews).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object reviews(Map<String, Object> params) {
        return reviews(params, null);
    }

    /**
     * ikea-reviews (GET /ikea/reviews). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object reviews(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("ikea-reviews", params);
        return client.request("ikea-reviews", params, options);
    }

    /**
     * ikea-search (GET /ikea/search).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object search(Map<String, Object> params) {
        return search(params, null);
    }

    /**
     * ikea-search (GET /ikea/search). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object search(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("ikea-search", params);
        return client.request("ikea-search", params, options);
    }

    /**
     * ikea-store (GET /ikea/store).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object store(Map<String, Object> params) {
        return store(params, null);
    }

    /**
     * ikea-store (GET /ikea/store). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object store(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("ikea-store", params);
        return client.request("ikea-store", params, options);
    }

    /**
     * ikea-stores (GET /ikea/stores).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object stores(Map<String, Object> params) {
        return stores(params, null);
    }

    /**
     * ikea-stores (GET /ikea/stores). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object stores(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("ikea-stores", params);
        return client.request("ikea-stores", params, options);
    }

    /**
     * ikea-stores (GET /ikea/stores). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object stores() {
        return stores(Map.of(), null);
    }

    /**
     * ikea-suggest (GET /ikea/suggest).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object suggest(Map<String, Object> params) {
        return suggest(params, null);
    }

    /**
     * ikea-suggest (GET /ikea/suggest). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object suggest(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("ikea-suggest", params);
        return client.request("ikea-suggest", params, options);
    }

}
