package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "importYeti" operation group.
 * Reach it via {@code client.importYeti()}.
 */
public final class ImportYetiGroup {
    private final CrawloraClient client;

    public ImportYetiGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * importyeti-company (GET /importyeti/company).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object importyetiCompany(Map<String, Object> params) {
        return importyetiCompany(params, null);
    }

    /**
     * importyeti-company (GET /importyeti/company). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object importyetiCompany(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("importyeti-company", params);
        return client.request("importyeti-company", params, options);
    }

    /**
     * importyeti-search (GET /importyeti/search).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object importyetiSearch(Map<String, Object> params) {
        return importyetiSearch(params, null);
    }

    /**
     * importyeti-search (GET /importyeti/search). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object importyetiSearch(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("importyeti-search", params);
        return client.request("importyeti-search", params, options);
    }

}
