package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "jobs" operation group.
 * Reach it via {@code client.jobs()}.
 */
public final class JobsGroup {
    private final CrawloraClient client;

    public JobsGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * jobs-ashby-board (GET /jobs/ashby/board).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object ashbyBoard(Map<String, Object> params) {
        return ashbyBoard(params, null);
    }

    /**
     * jobs-ashby-board (GET /jobs/ashby/board). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object ashbyBoard(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("jobs-ashby-board", params);
        return client.request("jobs-ashby-board", params, options);
    }

    /**
     * jobs-company-search (GET /jobs/company-search).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object companySearch(Map<String, Object> params) {
        return companySearch(params, null);
    }

    /**
     * jobs-company-search (GET /jobs/company-search). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object companySearch(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("jobs-company-search", params);
        return client.request("jobs-company-search", params, options);
    }

    /**
     * jobs-greenhouse-board (GET /jobs/greenhouse/board).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object greenhouseBoard(Map<String, Object> params) {
        return greenhouseBoard(params, null);
    }

    /**
     * jobs-greenhouse-board (GET /jobs/greenhouse/board). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object greenhouseBoard(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("jobs-greenhouse-board", params);
        return client.request("jobs-greenhouse-board", params, options);
    }

    /**
     * jobs-greenhouse-job (GET /jobs/greenhouse/job).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object greenhouseJob(Map<String, Object> params) {
        return greenhouseJob(params, null);
    }

    /**
     * jobs-greenhouse-job (GET /jobs/greenhouse/job). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object greenhouseJob(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("jobs-greenhouse-job", params);
        return client.request("jobs-greenhouse-job", params, options);
    }

    /**
     * jobs-hiring-signals (GET /jobs/hiring-signals).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object hiringSignals(Map<String, Object> params) {
        return hiringSignals(params, null);
    }

    /**
     * jobs-hiring-signals (GET /jobs/hiring-signals). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object hiringSignals(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("jobs-hiring-signals", params);
        return client.request("jobs-hiring-signals", params, options);
    }

    /**
     * jobs-lever-posting (GET /jobs/lever/posting).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object leverPosting(Map<String, Object> params) {
        return leverPosting(params, null);
    }

    /**
     * jobs-lever-posting (GET /jobs/lever/posting). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object leverPosting(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("jobs-lever-posting", params);
        return client.request("jobs-lever-posting", params, options);
    }

    /**
     * jobs-lever-postings (GET /jobs/lever/postings).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object leverPostings(Map<String, Object> params) {
        return leverPostings(params, null);
    }

    /**
     * jobs-lever-postings (GET /jobs/lever/postings). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object leverPostings(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("jobs-lever-postings", params);
        return client.request("jobs-lever-postings", params, options);
    }

    /**
     * jobs-smartrecruiters-posting (GET /jobs/smartrecruiters/posting).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object smartrecruitersPosting(Map<String, Object> params) {
        return smartrecruitersPosting(params, null);
    }

    /**
     * jobs-smartrecruiters-posting (GET /jobs/smartrecruiters/posting). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object smartrecruitersPosting(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("jobs-smartrecruiters-posting", params);
        return client.request("jobs-smartrecruiters-posting", params, options);
    }

    /**
     * jobs-smartrecruiters-postings (GET /jobs/smartrecruiters/postings).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object smartrecruitersPostings(Map<String, Object> params) {
        return smartrecruitersPostings(params, null);
    }

    /**
     * jobs-smartrecruiters-postings (GET /jobs/smartrecruiters/postings). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object smartrecruitersPostings(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("jobs-smartrecruiters-postings", params);
        return client.request("jobs-smartrecruiters-postings", params, options);
    }

    /**
     * jobs-workday-board (GET /jobs/workday/board).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object workdayBoard(Map<String, Object> params) {
        return workdayBoard(params, null);
    }

    /**
     * jobs-workday-board (GET /jobs/workday/board). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object workdayBoard(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("jobs-workday-board", params);
        return client.request("jobs-workday-board", params, options);
    }

    /**
     * jobs-workday-job (GET /jobs/workday/job).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object workdayJob(Map<String, Object> params) {
        return workdayJob(params, null);
    }

    /**
     * jobs-workday-job (GET /jobs/workday/job). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object workdayJob(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("jobs-workday-job", params);
        return client.request("jobs-workday-job", params, options);
    }

}
