package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "kickstarter" operation group.
 * Reach it via {@code client.kickstarter()}.
 */
public final class KickstarterGroup {
    private final CrawloraClient client;

    public KickstarterGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * kickstarter-comments (GET /kickstarter/comments).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object comments(Map<String, Object> params) {
        return comments(params, null);
    }

    /**
     * kickstarter-comments (GET /kickstarter/comments). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object comments(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("kickstarter-comments", params);
        return client.request("kickstarter-comments", params, options);
    }

    /**
     * kickstarter-discover (GET /kickstarter/discover).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object discover(Map<String, Object> params) {
        return discover(params, null);
    }

    /**
     * kickstarter-discover (GET /kickstarter/discover). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object discover(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("kickstarter-discover", params);
        return client.request("kickstarter-discover", params, options);
    }

    /**
     * kickstarter-discover (GET /kickstarter/discover). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object discover() {
        return discover(Map.of(), null);
    }

    /**
     * kickstarter-project (GET /kickstarter/project).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object project(Map<String, Object> params) {
        return project(params, null);
    }

    /**
     * kickstarter-project (GET /kickstarter/project). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object project(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("kickstarter-project", params);
        return client.request("kickstarter-project", params, options);
    }

    /**
     * kickstarter-updates (GET /kickstarter/updates).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object updates(Map<String, Object> params) {
        return updates(params, null);
    }

    /**
     * kickstarter-updates (GET /kickstarter/updates). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object updates(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("kickstarter-updates", params);
        return client.request("kickstarter-updates", params, options);
    }

}
