package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "kotaku" operation group.
 * Reach it via {@code client.kotaku()}.
 */
public final class KotakuGroup {
    private final CrawloraClient client;

    public KotakuGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * kotaku-article (GET /kotaku/article).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object article(Map<String, Object> params) {
        return article(params, null);
    }

    /**
     * kotaku-article (GET /kotaku/article). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object article(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("kotaku-article", params);
        return client.request("kotaku-article", params, options);
    }

    /**
     * kotaku-author (GET /kotaku/author).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object author(Map<String, Object> params) {
        return author(params, null);
    }

    /**
     * kotaku-author (GET /kotaku/author). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object author(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("kotaku-author", params);
        return client.request("kotaku-author", params, options);
    }

    /**
     * kotaku-headlines (GET /kotaku/headlines).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object headlines(Map<String, Object> params) {
        return headlines(params, null);
    }

    /**
     * kotaku-headlines (GET /kotaku/headlines). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object headlines(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("kotaku-headlines", params);
        return client.request("kotaku-headlines", params, options);
    }

    /**
     * kotaku-news (GET /kotaku/news).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object news(Map<String, Object> params) {
        return news(params, null);
    }

    /**
     * kotaku-news (GET /kotaku/news). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object news(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("kotaku-news", params);
        return client.request("kotaku-news", params, options);
    }

    /**
     * kotaku-news (GET /kotaku/news). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object news() {
        return news(Map.of(), null);
    }

    /**
     * kotaku-sections (GET /kotaku/sections).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sections(Map<String, Object> params) {
        return sections(params, null);
    }

    /**
     * kotaku-sections (GET /kotaku/sections). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sections(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("kotaku-sections", params);
        return client.request("kotaku-sections", params, options);
    }

    /**
     * kotaku-sections (GET /kotaku/sections). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sections() {
        return sections(Map.of(), null);
    }

}
