package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "kroger" operation group.
 * Reach it via {@code client.kroger()}.
 */
public final class KrogerGroup {
    private final CrawloraClient client;

    public KrogerGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * kroger-category (GET /kroger/category).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object category(Map<String, Object> params) {
        return category(params, null);
    }

    /**
     * kroger-category (GET /kroger/category). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object category(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("kroger-category", params);
        return client.request("kroger-category", params, options);
    }

    /**
     * kroger-coupons (GET /kroger/coupons).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object coupons(Map<String, Object> params) {
        return coupons(params, null);
    }

    /**
     * kroger-coupons (GET /kroger/coupons). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object coupons(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("kroger-coupons", params);
        return client.request("kroger-coupons", params, options);
    }

    /**
     * kroger-coupons (GET /kroger/coupons). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object coupons() {
        return coupons(Map.of(), null);
    }

    /**
     * kroger-product (GET /kroger/product).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object product(Map<String, Object> params) {
        return product(params, null);
    }

    /**
     * kroger-product (GET /kroger/product). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object product(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("kroger-product", params);
        return client.request("kroger-product", params, options);
    }

    /**
     * kroger-product-reviews (GET /kroger/product/reviews).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object productReviews(Map<String, Object> params) {
        return productReviews(params, null);
    }

    /**
     * kroger-product-reviews (GET /kroger/product/reviews). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object productReviews(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("kroger-product-reviews", params);
        return client.request("kroger-product-reviews", params, options);
    }

    /**
     * kroger-products (GET /kroger/products).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object products(Map<String, Object> params) {
        return products(params, null);
    }

    /**
     * kroger-products (GET /kroger/products). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object products(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("kroger-products", params);
        return client.request("kroger-products", params, options);
    }

    /**
     * kroger-related-tags (GET /kroger/related-tags).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object relatedTags(Map<String, Object> params) {
        return relatedTags(params, null);
    }

    /**
     * kroger-related-tags (GET /kroger/related-tags). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object relatedTags(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("kroger-related-tags", params);
        return client.request("kroger-related-tags", params, options);
    }

    /**
     * kroger-search (GET /kroger/search).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object search(Map<String, Object> params) {
        return search(params, null);
    }

    /**
     * kroger-search (GET /kroger/search). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object search(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("kroger-search", params);
        return client.request("kroger-search", params, options);
    }

    /**
     * kroger-store (GET /kroger/store).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object store(Map<String, Object> params) {
        return store(params, null);
    }

    /**
     * kroger-store (GET /kroger/store). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object store(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("kroger-store", params);
        return client.request("kroger-store", params, options);
    }

    /**
     * kroger-suggest (GET /kroger/suggest).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object suggest(Map<String, Object> params) {
        return suggest(params, null);
    }

    /**
     * kroger-suggest (GET /kroger/suggest). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object suggest(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("kroger-suggest", params);
        return client.request("kroger-suggest", params, options);
    }

    /**
     * kroger-suggest (GET /kroger/suggest). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object suggest() {
        return suggest(Map.of(), null);
    }

}
