package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "letterboxd" operation group.
 * Reach it via {@code client.letterboxd()}.
 */
public final class LetterboxdGroup {
    private final CrawloraClient client;

    public LetterboxdGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * letterboxd-film (GET /letterboxd/film/{slug}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object film(Map<String, Object> params) {
        return film(params, null);
    }

    /**
     * letterboxd-film (GET /letterboxd/film/{slug}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object film(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("letterboxd-film", params);
        return client.request("letterboxd-film", params, options);
    }

    /**
     * letterboxd-film-rating-histogram (GET /letterboxd/film/{slug}/rating-histogram).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object filmRatingHistogram(Map<String, Object> params) {
        return filmRatingHistogram(params, null);
    }

    /**
     * letterboxd-film-rating-histogram (GET /letterboxd/film/{slug}/rating-histogram). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object filmRatingHistogram(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("letterboxd-film-rating-histogram", params);
        return client.request("letterboxd-film-rating-histogram", params, options);
    }

    /**
     * letterboxd-film-reviews (GET /letterboxd/film/{slug}/reviews).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object filmReviews(Map<String, Object> params) {
        return filmReviews(params, null);
    }

    /**
     * letterboxd-film-reviews (GET /letterboxd/film/{slug}/reviews). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object filmReviews(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("letterboxd-film-reviews", params);
        return client.request("letterboxd-film-reviews", params, options);
    }

    /**
     * letterboxd-film-similar (GET /letterboxd/film/{slug}/similar).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object filmSimilar(Map<String, Object> params) {
        return filmSimilar(params, null);
    }

    /**
     * letterboxd-film-similar (GET /letterboxd/film/{slug}/similar). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object filmSimilar(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("letterboxd-film-similar", params);
        return client.request("letterboxd-film-similar", params, options);
    }

    /**
     * letterboxd-member (GET /letterboxd/member/{username}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object member(Map<String, Object> params) {
        return member(params, null);
    }

    /**
     * letterboxd-member (GET /letterboxd/member/{username}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object member(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("letterboxd-member", params);
        return client.request("letterboxd-member", params, options);
    }

    /**
     * letterboxd-person (GET /letterboxd/person/{slug}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object person(Map<String, Object> params) {
        return person(params, null);
    }

    /**
     * letterboxd-person (GET /letterboxd/person/{slug}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object person(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("letterboxd-person", params);
        return client.request("letterboxd-person", params, options);
    }

    /**
     * letterboxd-popular (GET /letterboxd/popular).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object popular(Map<String, Object> params) {
        return popular(params, null);
    }

    /**
     * letterboxd-popular (GET /letterboxd/popular). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object popular(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("letterboxd-popular", params);
        return client.request("letterboxd-popular", params, options);
    }

    /**
     * letterboxd-popular (GET /letterboxd/popular). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object popular() {
        return popular(Map.of(), null);
    }

    /**
     * letterboxd-search (GET /letterboxd/search).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object search(Map<String, Object> params) {
        return search(params, null);
    }

    /**
     * letterboxd-search (GET /letterboxd/search). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object search(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("letterboxd-search", params);
        return client.request("letterboxd-search", params, options);
    }

}
