package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "manga" operation group.
 * Reach it via {@code client.manga()}.
 */
public final class MangaGroup {
    private final CrawloraClient client;

    public MangaGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * manga-rankings (GET /manga/rankings).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object rankings(Map<String, Object> params) {
        return rankings(params, null);
    }

    /**
     * manga-rankings (GET /manga/rankings). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object rankings(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("manga-rankings", params);
        return client.request("manga-rankings", params, options);
    }

    /**
     * manga-rankings (GET /manga/rankings). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object rankings() {
        return rankings(Map.of(), null);
    }

    /**
     * manga-search (GET /manga/search).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object search(Map<String, Object> params) {
        return search(params, null);
    }

    /**
     * manga-search (GET /manga/search). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object search(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("manga-search", params);
        return client.request("manga-search", params, options);
    }

    /**
     * manga-title (GET /manga/title/{id}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object title(Map<String, Object> params) {
        return title(params, null);
    }

    /**
     * manga-title (GET /manga/title/{id}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object title(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("manga-title", params);
        return client.request("manga-title", params, options);
    }

}
