package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "papaJohnS" operation group.
 * Reach it via {@code client.papaJohnS()}.
 */
public final class PapaJohnSGroup {
    private final CrawloraClient client;

    public PapaJohnSGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * papajohns-allergens (GET /papajohns/allergens).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsAllergens(Map<String, Object> params) {
        return papajohnsAllergens(params, null);
    }

    /**
     * papajohns-allergens (GET /papajohns/allergens). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsAllergens(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("papajohns-allergens", params);
        return client.request("papajohns-allergens", params, options);
    }

    /**
     * papajohns-allergens (GET /papajohns/allergens). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsAllergens() {
        return papajohnsAllergens(Map.of(), null);
    }

    /**
     * papajohns-colombia-menu (GET /papajohns/colombia/menu).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsColombiaMenu(Map<String, Object> params) {
        return papajohnsColombiaMenu(params, null);
    }

    /**
     * papajohns-colombia-menu (GET /papajohns/colombia/menu). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsColombiaMenu(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("papajohns-colombia-menu", params);
        return client.request("papajohns-colombia-menu", params, options);
    }

    /**
     * papajohns-colombia-menu (GET /papajohns/colombia/menu). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsColombiaMenu() {
        return papajohnsColombiaMenu(Map.of(), null);
    }

    /**
     * papajohns-deals (GET /papajohns/deals).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsDeals(Map<String, Object> params) {
        return papajohnsDeals(params, null);
    }

    /**
     * papajohns-deals (GET /papajohns/deals). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsDeals(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("papajohns-deals", params);
        return client.request("papajohns-deals", params, options);
    }

    /**
     * papajohns-deals (GET /papajohns/deals). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsDeals() {
        return papajohnsDeals(Map.of(), null);
    }

    /**
     * papajohns-directory (GET /papajohns/directory).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsDirectory(Map<String, Object> params) {
        return papajohnsDirectory(params, null);
    }

    /**
     * papajohns-directory (GET /papajohns/directory). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsDirectory(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("papajohns-directory", params);
        return client.request("papajohns-directory", params, options);
    }

    /**
     * papajohns-directory (GET /papajohns/directory). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsDirectory() {
        return papajohnsDirectory(Map.of(), null);
    }

    /**
     * papajohns-elsalvador-menu (GET /papajohns/elsalvador/menu).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsElsalvadorMenu(Map<String, Object> params) {
        return papajohnsElsalvadorMenu(params, null);
    }

    /**
     * papajohns-elsalvador-menu (GET /papajohns/elsalvador/menu). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsElsalvadorMenu(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("papajohns-elsalvador-menu", params);
        return client.request("papajohns-elsalvador-menu", params, options);
    }

    /**
     * papajohns-elsalvador-menu (GET /papajohns/elsalvador/menu). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsElsalvadorMenu() {
        return papajohnsElsalvadorMenu(Map.of(), null);
    }

    /**
     * papajohns-india-deal (GET /papajohns/india/deal).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsIndiaDeal(Map<String, Object> params) {
        return papajohnsIndiaDeal(params, null);
    }

    /**
     * papajohns-india-deal (GET /papajohns/india/deal). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsIndiaDeal(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("papajohns-india-deal", params);
        return client.request("papajohns-india-deal", params, options);
    }

    /**
     * papajohns-india-menu (GET /papajohns/india/menu).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsIndiaMenu(Map<String, Object> params) {
        return papajohnsIndiaMenu(params, null);
    }

    /**
     * papajohns-india-menu (GET /papajohns/india/menu). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsIndiaMenu(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("papajohns-india-menu", params);
        return client.request("papajohns-india-menu", params, options);
    }

    /**
     * papajohns-india-menu (GET /papajohns/india/menu). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsIndiaMenu() {
        return papajohnsIndiaMenu(Map.of(), null);
    }

    /**
     * papajohns-india-menu-item (GET /papajohns/india/menu/item).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsIndiaMenuItem(Map<String, Object> params) {
        return papajohnsIndiaMenuItem(params, null);
    }

    /**
     * papajohns-india-menu-item (GET /papajohns/india/menu/item). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsIndiaMenuItem(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("papajohns-india-menu-item", params);
        return client.request("papajohns-india-menu-item", params, options);
    }

    /**
     * papajohns-india-stores (GET /papajohns/india/stores).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsIndiaStores(Map<String, Object> params) {
        return papajohnsIndiaStores(params, null);
    }

    /**
     * papajohns-india-stores (GET /papajohns/india/stores). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsIndiaStores(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("papajohns-india-stores", params);
        return client.request("papajohns-india-stores", params, options);
    }

    /**
     * papajohns-india-stores (GET /papajohns/india/stores). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsIndiaStores() {
        return papajohnsIndiaStores(Map.of(), null);
    }

    /**
     * papajohns-intl-deals (GET /papajohns/intl/deals).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsIntlDeals(Map<String, Object> params) {
        return papajohnsIntlDeals(params, null);
    }

    /**
     * papajohns-intl-deals (GET /papajohns/intl/deals). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsIntlDeals(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("papajohns-intl-deals", params);
        return client.request("papajohns-intl-deals", params, options);
    }

    /**
     * papajohns-intl-ingredients (GET /papajohns/intl/ingredients).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsIntlIngredients(Map<String, Object> params) {
        return papajohnsIntlIngredients(params, null);
    }

    /**
     * papajohns-intl-ingredients (GET /papajohns/intl/ingredients). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsIntlIngredients(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("papajohns-intl-ingredients", params);
        return client.request("papajohns-intl-ingredients", params, options);
    }

    /**
     * papajohns-intl-menu (GET /papajohns/intl/menu).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsIntlMenu(Map<String, Object> params) {
        return papajohnsIntlMenu(params, null);
    }

    /**
     * papajohns-intl-menu (GET /papajohns/intl/menu). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsIntlMenu(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("papajohns-intl-menu", params);
        return client.request("papajohns-intl-menu", params, options);
    }

    /**
     * papajohns-intl-offer (GET /papajohns/intl/offer).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsIntlOffer(Map<String, Object> params) {
        return papajohnsIntlOffer(params, null);
    }

    /**
     * papajohns-intl-offer (GET /papajohns/intl/offer). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsIntlOffer(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("papajohns-intl-offer", params);
        return client.request("papajohns-intl-offer", params, options);
    }

    /**
     * papajohns-intl-product (GET /papajohns/intl/product).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsIntlProduct(Map<String, Object> params) {
        return papajohnsIntlProduct(params, null);
    }

    /**
     * papajohns-intl-product (GET /papajohns/intl/product). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsIntlProduct(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("papajohns-intl-product", params);
        return client.request("papajohns-intl-product", params, options);
    }

    /**
     * papajohns-intl-stores (GET /papajohns/intl/stores).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsIntlStores(Map<String, Object> params) {
        return papajohnsIntlStores(params, null);
    }

    /**
     * papajohns-intl-stores (GET /papajohns/intl/stores). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsIntlStores(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("papajohns-intl-stores", params);
        return client.request("papajohns-intl-stores", params, options);
    }

    /**
     * papajohns-menu (GET /papajohns/menu).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsMenu(Map<String, Object> params) {
        return papajohnsMenu(params, null);
    }

    /**
     * papajohns-menu (GET /papajohns/menu). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsMenu(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("papajohns-menu", params);
        return client.request("papajohns-menu", params, options);
    }

    /**
     * papajohns-menu (GET /papajohns/menu). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsMenu() {
        return papajohnsMenu(Map.of(), null);
    }

    /**
     * papajohns-menu-item (GET /papajohns/menu/item).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsMenuItem(Map<String, Object> params) {
        return papajohnsMenuItem(params, null);
    }

    /**
     * papajohns-menu-item (GET /papajohns/menu/item). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsMenuItem(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("papajohns-menu-item", params);
        return client.request("papajohns-menu-item", params, options);
    }

    /**
     * papajohns-nearby (GET /papajohns/nearby).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsNearby(Map<String, Object> params) {
        return papajohnsNearby(params, null);
    }

    /**
     * papajohns-nearby (GET /papajohns/nearby). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsNearby(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("papajohns-nearby", params);
        return client.request("papajohns-nearby", params, options);
    }

    /**
     * papajohns-nutrition (GET /papajohns/nutrition).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsNutrition(Map<String, Object> params) {
        return papajohnsNutrition(params, null);
    }

    /**
     * papajohns-nutrition (GET /papajohns/nutrition). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsNutrition(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("papajohns-nutrition", params);
        return client.request("papajohns-nutrition", params, options);
    }

    /**
     * papajohns-peru-menu (GET /papajohns/peru/menu).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsPeruMenu(Map<String, Object> params) {
        return papajohnsPeruMenu(params, null);
    }

    /**
     * papajohns-peru-menu (GET /papajohns/peru/menu). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsPeruMenu(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("papajohns-peru-menu", params);
        return client.request("papajohns-peru-menu", params, options);
    }

    /**
     * papajohns-peru-menu (GET /papajohns/peru/menu). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsPeruMenu() {
        return papajohnsPeruMenu(Map.of(), null);
    }

    /**
     * papajohns-poland-menu (GET /papajohns/poland/menu).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsPolandMenu(Map<String, Object> params) {
        return papajohnsPolandMenu(params, null);
    }

    /**
     * papajohns-poland-menu (GET /papajohns/poland/menu). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsPolandMenu(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("papajohns-poland-menu", params);
        return client.request("papajohns-poland-menu", params, options);
    }

    /**
     * papajohns-poland-menu (GET /papajohns/poland/menu). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsPolandMenu() {
        return papajohnsPolandMenu(Map.of(), null);
    }

    /**
     * papajohns-russia-menu (GET /papajohns/russia/menu).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsRussiaMenu(Map<String, Object> params) {
        return papajohnsRussiaMenu(params, null);
    }

    /**
     * papajohns-russia-menu (GET /papajohns/russia/menu). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsRussiaMenu(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("papajohns-russia-menu", params);
        return client.request("papajohns-russia-menu", params, options);
    }

    /**
     * papajohns-russia-menu (GET /papajohns/russia/menu). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsRussiaMenu() {
        return papajohnsRussiaMenu(Map.of(), null);
    }

    /**
     * papajohns-store (GET /papajohns/store).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsStore(Map<String, Object> params) {
        return papajohnsStore(params, null);
    }

    /**
     * papajohns-store (GET /papajohns/store). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object papajohnsStore(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("papajohns-store", params);
        return client.request("papajohns-store", params, options);
    }

}
