package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "philstar" operation group.
 * Reach it via {@code client.philstar()}.
 */
public final class PhilstarGroup {
    private final CrawloraClient client;

    public PhilstarGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * philstar-article (GET /philstar/article).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object article(Map<String, Object> params) {
        return article(params, null);
    }

    /**
     * philstar-article (GET /philstar/article). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object article(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("philstar-article", params);
        return client.request("philstar-article", params, options);
    }

    /**
     * philstar-author (GET /philstar/author).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object author(Map<String, Object> params) {
        return author(params, null);
    }

    /**
     * philstar-author (GET /philstar/author). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object author(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("philstar-author", params);
        return client.request("philstar-author", params, options);
    }

    /**
     * philstar-author (GET /philstar/author). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object author() {
        return author(Map.of(), null);
    }

    /**
     * philstar-headlines (GET /philstar/headlines).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object headlines(Map<String, Object> params) {
        return headlines(params, null);
    }

    /**
     * philstar-headlines (GET /philstar/headlines). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object headlines(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("philstar-headlines", params);
        return client.request("philstar-headlines", params, options);
    }

    /**
     * philstar-news (GET /philstar/news).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object news(Map<String, Object> params) {
        return news(params, null);
    }

    /**
     * philstar-news (GET /philstar/news). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object news(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("philstar-news", params);
        return client.request("philstar-news", params, options);
    }

    /**
     * philstar-news (GET /philstar/news). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object news() {
        return news(Map.of(), null);
    }

    /**
     * philstar-sections (GET /philstar/sections).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sections(Map<String, Object> params) {
        return sections(params, null);
    }

    /**
     * philstar-sections (GET /philstar/sections). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sections(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("philstar-sections", params);
        return client.request("philstar-sections", params, options);
    }

    /**
     * philstar-sections (GET /philstar/sections). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sections() {
        return sections(Map.of(), null);
    }

}
