package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "polymarket" operation group.
 * Reach it via {@code client.polymarket()}.
 */
public final class PolymarketGroup {
    private final CrawloraClient client;

    public PolymarketGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * polymarket-activity-trades (GET /polymarket/activity/trades).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object activityTrades(Map<String, Object> params) {
        return activityTrades(params, null);
    }

    /**
     * polymarket-activity-trades (GET /polymarket/activity/trades). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object activityTrades(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-activity-trades", params);
        return client.request("polymarket-activity-trades", params, options);
    }

    /**
     * polymarket-activity-trades (GET /polymarket/activity/trades). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object activityTrades() {
        return activityTrades(Map.of(), null);
    }

    /**
     * polymarket-clob-market (GET /polymarket/clob/market/{condition_id}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object clobMarket(Map<String, Object> params) {
        return clobMarket(params, null);
    }

    /**
     * polymarket-clob-market (GET /polymarket/clob/market/{condition_id}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object clobMarket(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-clob-market", params);
        return client.request("polymarket-clob-market", params, options);
    }

    /**
     * polymarket-dashboard-macro (GET /polymarket/dashboards/macro).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object dashboardMacro(Map<String, Object> params) {
        return dashboardMacro(params, null);
    }

    /**
     * polymarket-dashboard-macro (GET /polymarket/dashboards/macro). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object dashboardMacro(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-dashboard-macro", params);
        return client.request("polymarket-dashboard-macro", params, options);
    }

    /**
     * polymarket-dashboard-macro (GET /polymarket/dashboards/macro). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object dashboardMacro() {
        return dashboardMacro(Map.of(), null);
    }

    /**
     * polymarket-data-followers (GET /polymarket/data/followers/{address}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object dataFollowers(Map<String, Object> params) {
        return dataFollowers(params, null);
    }

    /**
     * polymarket-data-followers (GET /polymarket/data/followers/{address}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object dataFollowers(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-data-followers", params);
        return client.request("polymarket-data-followers", params, options);
    }

    /**
     * polymarket-data-following (GET /polymarket/data/following/{address}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object dataFollowing(Map<String, Object> params) {
        return dataFollowing(params, null);
    }

    /**
     * polymarket-data-following (GET /polymarket/data/following/{address}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object dataFollowing(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-data-following", params);
        return client.request("polymarket-data-following", params, options);
    }

    /**
     * polymarket-data-follows-counts (GET /polymarket/data/follows/counts/{address}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object dataFollowsCounts(Map<String, Object> params) {
        return dataFollowsCounts(params, null);
    }

    /**
     * polymarket-data-follows-counts (GET /polymarket/data/follows/counts/{address}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object dataFollowsCounts(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-data-follows-counts", params);
        return client.request("polymarket-data-follows-counts", params, options);
    }

    /**
     * polymarket-event-detail-by-id (GET /polymarket/event/id/{id}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object eventDetailById(Map<String, Object> params) {
        return eventDetailById(params, null);
    }

    /**
     * polymarket-event-detail-by-id (GET /polymarket/event/id/{id}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object eventDetailById(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-event-detail-by-id", params);
        return client.request("polymarket-event-detail-by-id", params, options);
    }

    /**
     * polymarket-event-activity-by-id (GET /polymarket/event/id/{id}/activity).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object eventActivityById(Map<String, Object> params) {
        return eventActivityById(params, null);
    }

    /**
     * polymarket-event-activity-by-id (GET /polymarket/event/id/{id}/activity). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object eventActivityById(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-event-activity-by-id", params);
        return client.request("polymarket-event-activity-by-id", params, options);
    }

    /**
     * polymarket-event-detail (GET /polymarket/event/{slug}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object eventDetail(Map<String, Object> params) {
        return eventDetail(params, null);
    }

    /**
     * polymarket-event-detail (GET /polymarket/event/{slug}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object eventDetail(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-event-detail", params);
        return client.request("polymarket-event-detail", params, options);
    }

    /**
     * polymarket-event-activity (GET /polymarket/event/{slug}/activity).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object eventActivity(Map<String, Object> params) {
        return eventActivity(params, null);
    }

    /**
     * polymarket-event-activity (GET /polymarket/event/{slug}/activity). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object eventActivity(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-event-activity", params);
        return client.request("polymarket-event-activity", params, options);
    }

    /**
     * polymarket-events (GET /polymarket/events).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object events(Map<String, Object> params) {
        return events(params, null);
    }

    /**
     * polymarket-events (GET /polymarket/events). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object events(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-events", params);
        return client.request("polymarket-events", params, options);
    }

    /**
     * polymarket-events (GET /polymarket/events). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object events() {
        return events(Map.of(), null);
    }

    /**
     * polymarket-events-similar (GET /polymarket/events/similar).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object eventsSimilar(Map<String, Object> params) {
        return eventsSimilar(params, null);
    }

    /**
     * polymarket-events-similar (GET /polymarket/events/similar). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object eventsSimilar(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-events-similar", params);
        return client.request("polymarket-events-similar", params, options);
    }

    /**
     * polymarket-events-similar (GET /polymarket/events/similar). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object eventsSimilar() {
        return eventsSimilar(Map.of(), null);
    }

    /**
     * polymarket-event-tags (GET /polymarket/events/{id}/tags).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object eventTags(Map<String, Object> params) {
        return eventTags(params, null);
    }

    /**
     * polymarket-event-tags (GET /polymarket/events/{id}/tags). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object eventTags(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-event-tags", params);
        return client.request("polymarket-event-tags", params, options);
    }

    /**
     * polymarket-fee-types (GET /polymarket/fee-types).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object feeTypes(Map<String, Object> params) {
        return feeTypes(params, null);
    }

    /**
     * polymarket-fee-types (GET /polymarket/fee-types). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object feeTypes(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-fee-types", params);
        return client.request("polymarket-fee-types", params, options);
    }

    /**
     * polymarket-fee-types (GET /polymarket/fee-types). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object feeTypes() {
        return feeTypes(Map.of(), null);
    }

    /**
     * polymarket-games (GET /polymarket/games).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object games(Map<String, Object> params) {
        return games(params, null);
    }

    /**
     * polymarket-games (GET /polymarket/games). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object games(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-games", params);
        return client.request("polymarket-games", params, options);
    }

    /**
     * polymarket-games (GET /polymarket/games). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object games() {
        return games(Map.of(), null);
    }

    /**
     * polymarket-homepage-feed (GET /polymarket/homepage/feed).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object homepageFeed(Map<String, Object> params) {
        return homepageFeed(params, null);
    }

    /**
     * polymarket-homepage-feed (GET /polymarket/homepage/feed). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object homepageFeed(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-homepage-feed", params);
        return client.request("polymarket-homepage-feed", params, options);
    }

    /**
     * polymarket-homepage-feed (GET /polymarket/homepage/feed). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object homepageFeed() {
        return homepageFeed(Map.of(), null);
    }

    /**
     * polymarket-leaderboard (GET /polymarket/leaderboard).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object leaderboard(Map<String, Object> params) {
        return leaderboard(params, null);
    }

    /**
     * polymarket-leaderboard (GET /polymarket/leaderboard). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object leaderboard(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-leaderboard", params);
        return client.request("polymarket-leaderboard", params, options);
    }

    /**
     * polymarket-leaderboard (GET /polymarket/leaderboard). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object leaderboard() {
        return leaderboard(Map.of(), null);
    }

    /**
     * polymarket-market-clarifications (GET /polymarket/market-clarifications).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object marketClarifications(Map<String, Object> params) {
        return marketClarifications(params, null);
    }

    /**
     * polymarket-market-clarifications (GET /polymarket/market-clarifications). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object marketClarifications(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-market-clarifications", params);
        return client.request("polymarket-market-clarifications", params, options);
    }

    /**
     * polymarket-market-clarifications (GET /polymarket/market-clarifications). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object marketClarifications() {
        return marketClarifications(Map.of(), null);
    }

    /**
     * polymarket-market-detail-by-condition (GET /polymarket/market/condition/{condition_id}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object marketDetailByCondition(Map<String, Object> params) {
        return marketDetailByCondition(params, null);
    }

    /**
     * polymarket-market-detail-by-condition (GET /polymarket/market/condition/{condition_id}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object marketDetailByCondition(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-market-detail-by-condition", params);
        return client.request("polymarket-market-detail-by-condition", params, options);
    }

    /**
     * polymarket-market-activity-by-condition (GET /polymarket/market/condition/{condition_id}/activity).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object marketActivityByCondition(Map<String, Object> params) {
        return marketActivityByCondition(params, null);
    }

    /**
     * polymarket-market-activity-by-condition (GET /polymarket/market/condition/{condition_id}/activity). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object marketActivityByCondition(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-market-activity-by-condition", params);
        return client.request("polymarket-market-activity-by-condition", params, options);
    }

    /**
     * polymarket-market-liquidity-by-condition (GET /polymarket/market/condition/{condition_id}/liquidity).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object marketLiquidityByCondition(Map<String, Object> params) {
        return marketLiquidityByCondition(params, null);
    }

    /**
     * polymarket-market-liquidity-by-condition (GET /polymarket/market/condition/{condition_id}/liquidity). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object marketLiquidityByCondition(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-market-liquidity-by-condition", params);
        return client.request("polymarket-market-liquidity-by-condition", params, options);
    }

    /**
     * polymarket-market-detail-by-slug (GET /polymarket/market/slug/{slug}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object marketDetailBySlug(Map<String, Object> params) {
        return marketDetailBySlug(params, null);
    }

    /**
     * polymarket-market-detail-by-slug (GET /polymarket/market/slug/{slug}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object marketDetailBySlug(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-market-detail-by-slug", params);
        return client.request("polymarket-market-detail-by-slug", params, options);
    }

    /**
     * polymarket-market-liquidity-by-slug (GET /polymarket/market/slug/{slug}/liquidity).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object marketLiquidityBySlug(Map<String, Object> params) {
        return marketLiquidityBySlug(params, null);
    }

    /**
     * polymarket-market-liquidity-by-slug (GET /polymarket/market/slug/{slug}/liquidity). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object marketLiquidityBySlug(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-market-liquidity-by-slug", params);
        return client.request("polymarket-market-liquidity-by-slug", params, options);
    }

    /**
     * polymarket-market-detail (GET /polymarket/market/{id}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object marketDetail(Map<String, Object> params) {
        return marketDetail(params, null);
    }

    /**
     * polymarket-market-detail (GET /polymarket/market/{id}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object marketDetail(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-market-detail", params);
        return client.request("polymarket-market-detail", params, options);
    }

    /**
     * polymarket-market-liquidity (GET /polymarket/market/{id}/liquidity).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object marketLiquidity(Map<String, Object> params) {
        return marketLiquidity(params, null);
    }

    /**
     * polymarket-market-liquidity (GET /polymarket/market/{id}/liquidity). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object marketLiquidity(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-market-liquidity", params);
        return client.request("polymarket-market-liquidity", params, options);
    }

    /**
     * polymarket-market-tags (GET /polymarket/market/{id}/tags).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object marketTags(Map<String, Object> params) {
        return marketTags(params, null);
    }

    /**
     * polymarket-market-tags (GET /polymarket/market/{id}/tags). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object marketTags(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-market-tags", params);
        return client.request("polymarket-market-tags", params, options);
    }

    /**
     * polymarket-markets (GET /polymarket/markets).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object markets(Map<String, Object> params) {
        return markets(params, null);
    }

    /**
     * polymarket-markets (GET /polymarket/markets). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object markets(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-markets", params);
        return client.request("polymarket-markets", params, options);
    }

    /**
     * polymarket-markets (GET /polymarket/markets). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object markets() {
        return markets(Map.of(), null);
    }

    /**
     * polymarket-predictions (GET /polymarket/predictions).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object predictions(Map<String, Object> params) {
        return predictions(params, null);
    }

    /**
     * polymarket-predictions (GET /polymarket/predictions). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object predictions(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-predictions", params);
        return client.request("polymarket-predictions", params, options);
    }

    /**
     * polymarket-predictions (GET /polymarket/predictions). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object predictions() {
        return predictions(Map.of(), null);
    }

    /**
     * polymarket-rewards-market (GET /polymarket/rewards/market/{condition_id}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object rewardsMarket(Map<String, Object> params) {
        return rewardsMarket(params, null);
    }

    /**
     * polymarket-rewards-market (GET /polymarket/rewards/market/{condition_id}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object rewardsMarket(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-rewards-market", params);
        return client.request("polymarket-rewards-market", params, options);
    }

    /**
     * polymarket-rewards-markets (GET /polymarket/rewards/markets).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object rewardsMarkets(Map<String, Object> params) {
        return rewardsMarkets(params, null);
    }

    /**
     * polymarket-rewards-markets (GET /polymarket/rewards/markets). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object rewardsMarkets(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-rewards-markets", params);
        return client.request("polymarket-rewards-markets", params, options);
    }

    /**
     * polymarket-rewards-markets (GET /polymarket/rewards/markets). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object rewardsMarkets() {
        return rewardsMarkets(Map.of(), null);
    }

    /**
     * polymarket-search (GET /polymarket/search).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object search(Map<String, Object> params) {
        return search(params, null);
    }

    /**
     * polymarket-search (GET /polymarket/search). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object search(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-search", params);
        return client.request("polymarket-search", params, options);
    }

    /**
     * polymarket-sports (GET /polymarket/sports).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sports(Map<String, Object> params) {
        return sports(params, null);
    }

    /**
     * polymarket-sports (GET /polymarket/sports). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sports(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-sports", params);
        return client.request("polymarket-sports", params, options);
    }

    /**
     * polymarket-sports (GET /polymarket/sports). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sports() {
        return sports(Map.of(), null);
    }

    /**
     * polymarket-sports-by-partner (GET /polymarket/sports/by-partner).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sportsByPartner(Map<String, Object> params) {
        return sportsByPartner(params, null);
    }

    /**
     * polymarket-sports-by-partner (GET /polymarket/sports/by-partner). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sportsByPartner(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-sports-by-partner", params);
        return client.request("polymarket-sports-by-partner", params, options);
    }

    /**
     * polymarket-sports-by-partner (GET /polymarket/sports/by-partner). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sportsByPartner() {
        return sportsByPartner(Map.of(), null);
    }

    /**
     * polymarket-sports-market-types (GET /polymarket/sports/market-types).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sportsMarketTypes(Map<String, Object> params) {
        return sportsMarketTypes(params, null);
    }

    /**
     * polymarket-sports-market-types (GET /polymarket/sports/market-types). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sportsMarketTypes(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-sports-market-types", params);
        return client.request("polymarket-sports-market-types", params, options);
    }

    /**
     * polymarket-sports-market-types (GET /polymarket/sports/market-types). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sportsMarketTypes() {
        return sportsMarketTypes(Map.of(), null);
    }

    /**
     * polymarket-sports-summary (GET /polymarket/sports/summary).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sportsSummary(Map<String, Object> params) {
        return sportsSummary(params, null);
    }

    /**
     * polymarket-sports-summary (GET /polymarket/sports/summary). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sportsSummary(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-sports-summary", params);
        return client.request("polymarket-sports-summary", params, options);
    }

    /**
     * polymarket-sports-summary (GET /polymarket/sports/summary). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sportsSummary() {
        return sportsSummary(Map.of(), null);
    }

    /**
     * polymarket-sport (GET /polymarket/sports/{id}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sport(Map<String, Object> params) {
        return sport(params, null);
    }

    /**
     * polymarket-sport (GET /polymarket/sports/{id}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sport(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-sport", params);
        return client.request("polymarket-sport", params, options);
    }

    /**
     * polymarket-sport-external-partners (GET /polymarket/sports/{id}/external-partners).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sportExternalPartners(Map<String, Object> params) {
        return sportExternalPartners(params, null);
    }

    /**
     * polymarket-sport-external-partners (GET /polymarket/sports/{id}/external-partners). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sportExternalPartners(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-sport-external-partners", params);
        return client.request("polymarket-sport-external-partners", params, options);
    }

    /**
     * polymarket-sport-external-partner (GET /polymarket/sports/{id}/external-partners/{partner_ref}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sportExternalPartner(Map<String, Object> params) {
        return sportExternalPartner(params, null);
    }

    /**
     * polymarket-sport-external-partner (GET /polymarket/sports/{id}/external-partners/{partner_ref}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sportExternalPartner(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-sport-external-partner", params);
        return client.request("polymarket-sport-external-partner", params, options);
    }

    /**
     * polymarket-spotlights (GET /polymarket/spotlights).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object spotlights(Map<String, Object> params) {
        return spotlights(params, null);
    }

    /**
     * polymarket-spotlights (GET /polymarket/spotlights). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object spotlights(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-spotlights", params);
        return client.request("polymarket-spotlights", params, options);
    }

    /**
     * polymarket-spotlights (GET /polymarket/spotlights). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object spotlights() {
        return spotlights(Map.of(), null);
    }

    /**
     * polymarket-spotlights-keyset (GET /polymarket/spotlights/keyset).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object spotlightsKeyset(Map<String, Object> params) {
        return spotlightsKeyset(params, null);
    }

    /**
     * polymarket-spotlights-keyset (GET /polymarket/spotlights/keyset). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object spotlightsKeyset(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-spotlights-keyset", params);
        return client.request("polymarket-spotlights-keyset", params, options);
    }

    /**
     * polymarket-spotlights-keyset (GET /polymarket/spotlights/keyset). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object spotlightsKeyset() {
        return spotlightsKeyset(Map.of(), null);
    }

    /**
     * polymarket-spotlight (GET /polymarket/spotlights/{slug}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object spotlight(Map<String, Object> params) {
        return spotlight(params, null);
    }

    /**
     * polymarket-spotlight (GET /polymarket/spotlights/{slug}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object spotlight(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-spotlight", params);
        return client.request("polymarket-spotlight", params, options);
    }

    /**
     * polymarket-status (GET /polymarket/status).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object status(Map<String, Object> params) {
        return status(params, null);
    }

    /**
     * polymarket-status (GET /polymarket/status). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object status(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-status", params);
        return client.request("polymarket-status", params, options);
    }

    /**
     * polymarket-status (GET /polymarket/status). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object status() {
        return status(Map.of(), null);
    }

    /**
     * polymarket-tag-by-slug (GET /polymarket/tag/slug/{slug}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object tagBySlug(Map<String, Object> params) {
        return tagBySlug(params, null);
    }

    /**
     * polymarket-tag-by-slug (GET /polymarket/tag/slug/{slug}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object tagBySlug(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-tag-by-slug", params);
        return client.request("polymarket-tag-by-slug", params, options);
    }

    /**
     * polymarket-related-tags-by-slug (GET /polymarket/tag/slug/{slug}/related-tags).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object relatedTagsBySlug(Map<String, Object> params) {
        return relatedTagsBySlug(params, null);
    }

    /**
     * polymarket-related-tags-by-slug (GET /polymarket/tag/slug/{slug}/related-tags). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object relatedTagsBySlug(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-related-tags-by-slug", params);
        return client.request("polymarket-related-tags-by-slug", params, options);
    }

    /**
     * polymarket-related-tag-rows-by-slug (GET /polymarket/tag/slug/{slug}/related-tags/tags).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object relatedTagRowsBySlug(Map<String, Object> params) {
        return relatedTagRowsBySlug(params, null);
    }

    /**
     * polymarket-related-tag-rows-by-slug (GET /polymarket/tag/slug/{slug}/related-tags/tags). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object relatedTagRowsBySlug(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-related-tag-rows-by-slug", params);
        return client.request("polymarket-related-tag-rows-by-slug", params, options);
    }

    /**
     * polymarket-tag (GET /polymarket/tag/{id}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object tag(Map<String, Object> params) {
        return tag(params, null);
    }

    /**
     * polymarket-tag (GET /polymarket/tag/{id}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object tag(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-tag", params);
        return client.request("polymarket-tag", params, options);
    }

    /**
     * polymarket-related-tags (GET /polymarket/tag/{id}/related-tags).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object relatedTags(Map<String, Object> params) {
        return relatedTags(params, null);
    }

    /**
     * polymarket-related-tags (GET /polymarket/tag/{id}/related-tags). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object relatedTags(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-related-tags", params);
        return client.request("polymarket-related-tags", params, options);
    }

    /**
     * polymarket-related-tag-rows (GET /polymarket/tag/{id}/related-tags/tags).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object relatedTagRows(Map<String, Object> params) {
        return relatedTagRows(params, null);
    }

    /**
     * polymarket-related-tag-rows (GET /polymarket/tag/{id}/related-tags/tags). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object relatedTagRows(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-related-tag-rows", params);
        return client.request("polymarket-related-tag-rows", params, options);
    }

    /**
     * polymarket-tags (GET /polymarket/tags).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object tags(Map<String, Object> params) {
        return tags(params, null);
    }

    /**
     * polymarket-tags (GET /polymarket/tags). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object tags(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-tags", params);
        return client.request("polymarket-tags", params, options);
    }

    /**
     * polymarket-tags (GET /polymarket/tags). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object tags() {
        return tags(Map.of(), null);
    }

    /**
     * polymarket-teams (GET /polymarket/teams).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object teams(Map<String, Object> params) {
        return teams(params, null);
    }

    /**
     * polymarket-teams (GET /polymarket/teams). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object teams(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-teams", params);
        return client.request("polymarket-teams", params, options);
    }

    /**
     * polymarket-teams (GET /polymarket/teams). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object teams() {
        return teams(Map.of(), null);
    }

    /**
     * polymarket-teams-by-partner (GET /polymarket/teams/by-partner).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object teamsByPartner(Map<String, Object> params) {
        return teamsByPartner(params, null);
    }

    /**
     * polymarket-teams-by-partner (GET /polymarket/teams/by-partner). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object teamsByPartner(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-teams-by-partner", params);
        return client.request("polymarket-teams-by-partner", params, options);
    }

    /**
     * polymarket-teams-by-partner (GET /polymarket/teams/by-partner). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object teamsByPartner() {
        return teamsByPartner(Map.of(), null);
    }

    /**
     * polymarket-team (GET /polymarket/teams/{id}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object team(Map<String, Object> params) {
        return team(params, null);
    }

    /**
     * polymarket-team (GET /polymarket/teams/{id}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object team(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-team", params);
        return client.request("polymarket-team", params, options);
    }

    /**
     * polymarket-team-external-partners (GET /polymarket/teams/{id}/external-partners).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object teamExternalPartners(Map<String, Object> params) {
        return teamExternalPartners(params, null);
    }

    /**
     * polymarket-team-external-partners (GET /polymarket/teams/{id}/external-partners). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object teamExternalPartners(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-team-external-partners", params);
        return client.request("polymarket-team-external-partners", params, options);
    }

    /**
     * polymarket-team-external-partner (GET /polymarket/teams/{id}/external-partners/{partner_ref}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object teamExternalPartner(Map<String, Object> params) {
        return teamExternalPartner(params, null);
    }

    /**
     * polymarket-team-external-partner (GET /polymarket/teams/{id}/external-partners/{partner_ref}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object teamExternalPartner(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-team-external-partner", params);
        return client.request("polymarket-team-external-partner", params, options);
    }

    /**
     * polymarket-token-midpoint (GET /polymarket/token/{token_id}/midpoint).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object tokenMidpoint(Map<String, Object> params) {
        return tokenMidpoint(params, null);
    }

    /**
     * polymarket-token-midpoint (GET /polymarket/token/{token_id}/midpoint). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object tokenMidpoint(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-token-midpoint", params);
        return client.request("polymarket-token-midpoint", params, options);
    }

    /**
     * polymarket-token-orderbook (GET /polymarket/token/{token_id}/orderbook).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object tokenOrderbook(Map<String, Object> params) {
        return tokenOrderbook(params, null);
    }

    /**
     * polymarket-token-orderbook (GET /polymarket/token/{token_id}/orderbook). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object tokenOrderbook(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-token-orderbook", params);
        return client.request("polymarket-token-orderbook", params, options);
    }

    /**
     * polymarket-token-price (GET /polymarket/token/{token_id}/price).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object tokenPrice(Map<String, Object> params) {
        return tokenPrice(params, null);
    }

    /**
     * polymarket-token-price (GET /polymarket/token/{token_id}/price). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object tokenPrice(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-token-price", params);
        return client.request("polymarket-token-price", params, options);
    }

    /**
     * polymarket-token-price-history (GET /polymarket/token/{token_id}/price-history).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object tokenPriceHistory(Map<String, Object> params) {
        return tokenPriceHistory(params, null);
    }

    /**
     * polymarket-token-price-history (GET /polymarket/token/{token_id}/price-history). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object tokenPriceHistory(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-token-price-history", params);
        return client.request("polymarket-token-price-history", params, options);
    }

    /**
     * polymarket-token-spread (GET /polymarket/token/{token_id}/spread).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object tokenSpread(Map<String, Object> params) {
        return tokenSpread(params, null);
    }

    /**
     * polymarket-token-spread (GET /polymarket/token/{token_id}/spread). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object tokenSpread(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-token-spread", params);
        return client.request("polymarket-token-spread", params, options);
    }

    /**
     * polymarket-tokens-midpoints (POST /polymarket/tokens/midpoints).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object tokensMidpoints(Map<String, Object> params) {
        return tokensMidpoints(params, null);
    }

    /**
     * polymarket-tokens-midpoints (POST /polymarket/tokens/midpoints). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object tokensMidpoints(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-tokens-midpoints", params);
        return client.request("polymarket-tokens-midpoints", params, options);
    }

    /**
     * polymarket-tokens-orderbooks (POST /polymarket/tokens/orderbooks).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object tokensOrderbooks(Map<String, Object> params) {
        return tokensOrderbooks(params, null);
    }

    /**
     * polymarket-tokens-orderbooks (POST /polymarket/tokens/orderbooks). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object tokensOrderbooks(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-tokens-orderbooks", params);
        return client.request("polymarket-tokens-orderbooks", params, options);
    }

    /**
     * polymarket-tokens-prices (POST /polymarket/tokens/prices).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object tokensPrices(Map<String, Object> params) {
        return tokensPrices(params, null);
    }

    /**
     * polymarket-tokens-prices (POST /polymarket/tokens/prices). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object tokensPrices(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-tokens-prices", params);
        return client.request("polymarket-tokens-prices", params, options);
    }

    /**
     * polymarket-tokens-spreads (POST /polymarket/tokens/spreads).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object tokensSpreads(Map<String, Object> params) {
        return tokensSpreads(params, null);
    }

    /**
     * polymarket-tokens-spreads (POST /polymarket/tokens/spreads). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object tokensSpreads(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-tokens-spreads", params);
        return client.request("polymarket-tokens-spreads", params, options);
    }

    /**
     * polymarket-tournaments (GET /polymarket/tournaments).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object tournaments(Map<String, Object> params) {
        return tournaments(params, null);
    }

    /**
     * polymarket-tournaments (GET /polymarket/tournaments). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object tournaments(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-tournaments", params);
        return client.request("polymarket-tournaments", params, options);
    }

    /**
     * polymarket-tournaments (GET /polymarket/tournaments). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object tournaments() {
        return tournaments(Map.of(), null);
    }

    /**
     * polymarket-tournament (GET /polymarket/tournaments/{id}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object tournament(Map<String, Object> params) {
        return tournament(params, null);
    }

    /**
     * polymarket-tournament (GET /polymarket/tournaments/{id}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object tournament(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("polymarket-tournament", params);
        return client.request("polymarket-tournament", params, options);
    }

}
