package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "proPublica" operation group.
 * Reach it via {@code client.proPublica()}.
 */
public final class ProPublicaGroup {
    private final CrawloraClient client;

    public ProPublicaGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * propublica-article (GET /propublica/article).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object propublicaArticle(Map<String, Object> params) {
        return propublicaArticle(params, null);
    }

    /**
     * propublica-article (GET /propublica/article). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object propublicaArticle(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("propublica-article", params);
        return client.request("propublica-article", params, options);
    }

    /**
     * propublica-author (GET /propublica/author).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object propublicaAuthor(Map<String, Object> params) {
        return propublicaAuthor(params, null);
    }

    /**
     * propublica-author (GET /propublica/author). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object propublicaAuthor(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("propublica-author", params);
        return client.request("propublica-author", params, options);
    }

    /**
     * propublica-headlines (GET /propublica/headlines).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object propublicaHeadlines(Map<String, Object> params) {
        return propublicaHeadlines(params, null);
    }

    /**
     * propublica-headlines (GET /propublica/headlines). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object propublicaHeadlines(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("propublica-headlines", params);
        return client.request("propublica-headlines", params, options);
    }

    /**
     * propublica-news (GET /propublica/news).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object propublicaNews(Map<String, Object> params) {
        return propublicaNews(params, null);
    }

    /**
     * propublica-news (GET /propublica/news). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object propublicaNews(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("propublica-news", params);
        return client.request("propublica-news", params, options);
    }

    /**
     * propublica-news (GET /propublica/news). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object propublicaNews() {
        return propublicaNews(Map.of(), null);
    }

    /**
     * propublica-sections (GET /propublica/sections).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object propublicaSections(Map<String, Object> params) {
        return propublicaSections(params, null);
    }

    /**
     * propublica-sections (GET /propublica/sections). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object propublicaSections(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("propublica-sections", params);
        return client.request("propublica-sections", params, options);
    }

    /**
     * propublica-sections (GET /propublica/sections). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object propublicaSections() {
        return propublicaSections(Map.of(), null);
    }

}
