package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "retailMeNot" operation group.
 * Reach it via {@code client.retailMeNot()}.
 */
public final class RetailMeNotGroup {
    private final CrawloraClient client;

    public RetailMeNotGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * retailmenot-autocomplete (GET /retailmenot/autocomplete).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object retailmenotAutocomplete(Map<String, Object> params) {
        return retailmenotAutocomplete(params, null);
    }

    /**
     * retailmenot-autocomplete (GET /retailmenot/autocomplete). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object retailmenotAutocomplete(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("retailmenot-autocomplete", params);
        return client.request("retailmenot-autocomplete", params, options);
    }

    /**
     * retailmenot-blog-categories (GET /retailmenot/blog-categories).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object retailmenotBlogCategories(Map<String, Object> params) {
        return retailmenotBlogCategories(params, null);
    }

    /**
     * retailmenot-blog-categories (GET /retailmenot/blog-categories). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object retailmenotBlogCategories(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("retailmenot-blog-categories", params);
        return client.request("retailmenot-blog-categories", params, options);
    }

    /**
     * retailmenot-blog-categories (GET /retailmenot/blog-categories). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object retailmenotBlogCategories() {
        return retailmenotBlogCategories(Map.of(), null);
    }

    /**
     * retailmenot-blog-post (GET /retailmenot/blog-post).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object retailmenotBlogPost(Map<String, Object> params) {
        return retailmenotBlogPost(params, null);
    }

    /**
     * retailmenot-blog-post (GET /retailmenot/blog-post). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object retailmenotBlogPost(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("retailmenot-blog-post", params);
        return client.request("retailmenot-blog-post", params, options);
    }

    /**
     * retailmenot-blog-posts (GET /retailmenot/blog-posts).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object retailmenotBlogPosts(Map<String, Object> params) {
        return retailmenotBlogPosts(params, null);
    }

    /**
     * retailmenot-blog-posts (GET /retailmenot/blog-posts). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object retailmenotBlogPosts(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("retailmenot-blog-posts", params);
        return client.request("retailmenot-blog-posts", params, options);
    }

    /**
     * retailmenot-blog-posts (GET /retailmenot/blog-posts). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object retailmenotBlogPosts() {
        return retailmenotBlogPosts(Map.of(), null);
    }

    /**
     * retailmenot-blog-tags (GET /retailmenot/blog-tags).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object retailmenotBlogTags(Map<String, Object> params) {
        return retailmenotBlogTags(params, null);
    }

    /**
     * retailmenot-blog-tags (GET /retailmenot/blog-tags). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object retailmenotBlogTags(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("retailmenot-blog-tags", params);
        return client.request("retailmenot-blog-tags", params, options);
    }

    /**
     * retailmenot-blog-tags (GET /retailmenot/blog-tags). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object retailmenotBlogTags() {
        return retailmenotBlogTags(Map.of(), null);
    }

    /**
     * retailmenot-cashback (GET /retailmenot/cashback).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object retailmenotCashback(Map<String, Object> params) {
        return retailmenotCashback(params, null);
    }

    /**
     * retailmenot-cashback (GET /retailmenot/cashback). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object retailmenotCashback(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("retailmenot-cashback", params);
        return client.request("retailmenot-cashback", params, options);
    }

    /**
     * retailmenot-cashback (GET /retailmenot/cashback). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object retailmenotCashback() {
        return retailmenotCashback(Map.of(), null);
    }

    /**
     * retailmenot-categories (GET /retailmenot/categories).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object retailmenotCategories(Map<String, Object> params) {
        return retailmenotCategories(params, null);
    }

    /**
     * retailmenot-categories (GET /retailmenot/categories). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object retailmenotCategories(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("retailmenot-categories", params);
        return client.request("retailmenot-categories", params, options);
    }

    /**
     * retailmenot-categories (GET /retailmenot/categories). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object retailmenotCategories() {
        return retailmenotCategories(Map.of(), null);
    }

    /**
     * retailmenot-category (GET /retailmenot/category).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object retailmenotCategory(Map<String, Object> params) {
        return retailmenotCategory(params, null);
    }

    /**
     * retailmenot-category (GET /retailmenot/category). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object retailmenotCategory(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("retailmenot-category", params);
        return client.request("retailmenot-category", params, options);
    }

    /**
     * retailmenot-deal-event (GET /retailmenot/deal-event).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object retailmenotDealEvent(Map<String, Object> params) {
        return retailmenotDealEvent(params, null);
    }

    /**
     * retailmenot-deal-event (GET /retailmenot/deal-event). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object retailmenotDealEvent(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("retailmenot-deal-event", params);
        return client.request("retailmenot-deal-event", params, options);
    }

    /**
     * retailmenot-deal-events (GET /retailmenot/deal-events).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object retailmenotDealEvents(Map<String, Object> params) {
        return retailmenotDealEvents(params, null);
    }

    /**
     * retailmenot-deal-events (GET /retailmenot/deal-events). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object retailmenotDealEvents(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("retailmenot-deal-events", params);
        return client.request("retailmenot-deal-events", params, options);
    }

    /**
     * retailmenot-deal-events (GET /retailmenot/deal-events). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object retailmenotDealEvents() {
        return retailmenotDealEvents(Map.of(), null);
    }

    /**
     * retailmenot-home (GET /retailmenot/home).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object retailmenotHome(Map<String, Object> params) {
        return retailmenotHome(params, null);
    }

    /**
     * retailmenot-home (GET /retailmenot/home). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object retailmenotHome(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("retailmenot-home", params);
        return client.request("retailmenot-home", params, options);
    }

    /**
     * retailmenot-home (GET /retailmenot/home). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object retailmenotHome() {
        return retailmenotHome(Map.of(), null);
    }

    /**
     * retailmenot-store (GET /retailmenot/store).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object retailmenotStore(Map<String, Object> params) {
        return retailmenotStore(params, null);
    }

    /**
     * retailmenot-store (GET /retailmenot/store). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object retailmenotStore(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("retailmenot-store", params);
        return client.request("retailmenot-store", params, options);
    }

    /**
     * retailmenot-stores (GET /retailmenot/stores).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object retailmenotStores(Map<String, Object> params) {
        return retailmenotStores(params, null);
    }

    /**
     * retailmenot-stores (GET /retailmenot/stores). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object retailmenotStores(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("retailmenot-stores", params);
        return client.request("retailmenot-stores", params, options);
    }

}
