package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "salon" operation group.
 * Reach it via {@code client.salon()}.
 */
public final class SalonGroup {
    private final CrawloraClient client;

    public SalonGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * salon-article (GET /salon/article).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object article(Map<String, Object> params) {
        return article(params, null);
    }

    /**
     * salon-article (GET /salon/article). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object article(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("salon-article", params);
        return client.request("salon-article", params, options);
    }

    /**
     * salon-author (GET /salon/author).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object author(Map<String, Object> params) {
        return author(params, null);
    }

    /**
     * salon-author (GET /salon/author). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object author(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("salon-author", params);
        return client.request("salon-author", params, options);
    }

    /**
     * salon-headlines (GET /salon/headlines).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object headlines(Map<String, Object> params) {
        return headlines(params, null);
    }

    /**
     * salon-headlines (GET /salon/headlines). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object headlines(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("salon-headlines", params);
        return client.request("salon-headlines", params, options);
    }

    /**
     * salon-news (GET /salon/news).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object news(Map<String, Object> params) {
        return news(params, null);
    }

    /**
     * salon-news (GET /salon/news). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object news(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("salon-news", params);
        return client.request("salon-news", params, options);
    }

    /**
     * salon-news (GET /salon/news). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object news() {
        return news(Map.of(), null);
    }

    /**
     * salon-sections (GET /salon/sections).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sections(Map<String, Object> params) {
        return sections(params, null);
    }

    /**
     * salon-sections (GET /salon/sections). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sections(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("salon-sections", params);
        return client.request("salon-sections", params, options);
    }

    /**
     * salon-sections (GET /salon/sections). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sections() {
        return sections(Map.of(), null);
    }

}
