package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "scienceAlert" operation group.
 * Reach it via {@code client.scienceAlert()}.
 */
public final class ScienceAlertGroup {
    private final CrawloraClient client;

    public ScienceAlertGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * sciencealert-article (GET /sciencealert/article).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sciencealertArticle(Map<String, Object> params) {
        return sciencealertArticle(params, null);
    }

    /**
     * sciencealert-article (GET /sciencealert/article). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sciencealertArticle(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("sciencealert-article", params);
        return client.request("sciencealert-article", params, options);
    }

    /**
     * sciencealert-author (GET /sciencealert/author).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sciencealertAuthor(Map<String, Object> params) {
        return sciencealertAuthor(params, null);
    }

    /**
     * sciencealert-author (GET /sciencealert/author). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sciencealertAuthor(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("sciencealert-author", params);
        return client.request("sciencealert-author", params, options);
    }

    /**
     * sciencealert-headlines (GET /sciencealert/headlines).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sciencealertHeadlines(Map<String, Object> params) {
        return sciencealertHeadlines(params, null);
    }

    /**
     * sciencealert-headlines (GET /sciencealert/headlines). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sciencealertHeadlines(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("sciencealert-headlines", params);
        return client.request("sciencealert-headlines", params, options);
    }

    /**
     * sciencealert-news (GET /sciencealert/news).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sciencealertNews(Map<String, Object> params) {
        return sciencealertNews(params, null);
    }

    /**
     * sciencealert-news (GET /sciencealert/news). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sciencealertNews(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("sciencealert-news", params);
        return client.request("sciencealert-news", params, options);
    }

    /**
     * sciencealert-news (GET /sciencealert/news). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sciencealertNews() {
        return sciencealertNews(Map.of(), null);
    }

    /**
     * sciencealert-sections (GET /sciencealert/sections).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sciencealertSections(Map<String, Object> params) {
        return sciencealertSections(params, null);
    }

    /**
     * sciencealert-sections (GET /sciencealert/sections). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sciencealertSections(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("sciencealert-sections", params);
        return client.request("sciencealert-sections", params, options);
    }

    /**
     * sciencealert-sections (GET /sciencealert/sections). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sciencealertSections() {
        return sciencealertSections(Map.of(), null);
    }

}
