package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "startpage" operation group.
 * Reach it via {@code client.startpage()}.
 */
public final class StartpageGroup {
    private final CrawloraClient client;

    public StartpageGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * startpage-suggest (GET /startpage/suggest).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object suggest(Map<String, Object> params) {
        return suggest(params, null);
    }

    /**
     * startpage-suggest (GET /startpage/suggest). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object suggest(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("startpage-suggest", params);
        return client.request("startpage-suggest", params, options);
    }

}
