package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "subway" operation group.
 * Reach it via {@code client.subway()}.
 */
public final class SubwayGroup {
    private final CrawloraClient client;

    public SubwayGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * subway-available-times (GET /subway/available-times).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object availableTimes(Map<String, Object> params) {
        return availableTimes(params, null);
    }

    /**
     * subway-available-times (GET /subway/available-times). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object availableTimes(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("subway-available-times", params);
        return client.request("subway-available-times", params, options);
    }

    /**
     * subway-combos (GET /subway/combos).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object combos(Map<String, Object> params) {
        return combos(params, null);
    }

    /**
     * subway-combos (GET /subway/combos). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object combos(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("subway-combos", params);
        return client.request("subway-combos", params, options);
    }

    /**
     * subway-menu (GET /subway/menu).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object menu(Map<String, Object> params) {
        return menu(params, null);
    }

    /**
     * subway-menu (GET /subway/menu). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object menu(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("subway-menu", params);
        return client.request("subway-menu", params, options);
    }

    /**
     * subway-nearby (GET /subway/nearby).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object nearby(Map<String, Object> params) {
        return nearby(params, null);
    }

    /**
     * subway-nearby (GET /subway/nearby). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object nearby(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("subway-nearby", params);
        return client.request("subway-nearby", params, options);
    }

    /**
     * subway-nearby (GET /subway/nearby). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object nearby() {
        return nearby(Map.of(), null);
    }

    /**
     * subway-sitemap (GET /subway/sitemap).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sitemap(Map<String, Object> params) {
        return sitemap(params, null);
    }

    /**
     * subway-sitemap (GET /subway/sitemap). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sitemap(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("subway-sitemap", params);
        return client.request("subway-sitemap", params, options);
    }

    /**
     * subway-sitemap (GET /subway/sitemap). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sitemap() {
        return sitemap(Map.of(), null);
    }

    /**
     * subway-store (GET /subway/store).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object store(Map<String, Object> params) {
        return store(params, null);
    }

    /**
     * subway-store (GET /subway/store). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object store(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("subway-store", params);
        return client.request("subway-store", params, options);
    }

}
