package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "teslaJobs" operation group.
 * Reach it via {@code client.teslaJobs()}.
 */
public final class TeslaJobsGroup {
    private final CrawloraClient client;

    public TeslaJobsGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * tesla-jobs-job (GET /tesla-jobs/job).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object job(Map<String, Object> params) {
        return job(params, null);
    }

    /**
     * tesla-jobs-job (GET /tesla-jobs/job). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object job(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("tesla-jobs-job", params);
        return client.request("tesla-jobs-job", params, options);
    }

    /**
     * tesla-jobs-list (GET /tesla-jobs/list).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object list(Map<String, Object> params) {
        return list(params, null);
    }

    /**
     * tesla-jobs-list (GET /tesla-jobs/list). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object list(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("tesla-jobs-list", params);
        return client.request("tesla-jobs-list", params, options);
    }

    /**
     * tesla-jobs-list (GET /tesla-jobs/list). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object list() {
        return list(Map.of(), null);
    }

}
