package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "theNewYorker" operation group.
 * Reach it via {@code client.theNewYorker()}.
 */
public final class TheNewYorkerGroup {
    private final CrawloraClient client;

    public TheNewYorkerGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * newyorker-article (GET /newyorker/article).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object newyorkerArticle(Map<String, Object> params) {
        return newyorkerArticle(params, null);
    }

    /**
     * newyorker-article (GET /newyorker/article). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object newyorkerArticle(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("newyorker-article", params);
        return client.request("newyorker-article", params, options);
    }

    /**
     * newyorker-author (GET /newyorker/author).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object newyorkerAuthor(Map<String, Object> params) {
        return newyorkerAuthor(params, null);
    }

    /**
     * newyorker-author (GET /newyorker/author). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object newyorkerAuthor(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("newyorker-author", params);
        return client.request("newyorker-author", params, options);
    }

    /**
     * newyorker-headlines (GET /newyorker/headlines).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object newyorkerHeadlines(Map<String, Object> params) {
        return newyorkerHeadlines(params, null);
    }

    /**
     * newyorker-headlines (GET /newyorker/headlines). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object newyorkerHeadlines(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("newyorker-headlines", params);
        return client.request("newyorker-headlines", params, options);
    }

    /**
     * newyorker-news (GET /newyorker/news).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object newyorkerNews(Map<String, Object> params) {
        return newyorkerNews(params, null);
    }

    /**
     * newyorker-news (GET /newyorker/news). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object newyorkerNews(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("newyorker-news", params);
        return client.request("newyorker-news", params, options);
    }

    /**
     * newyorker-news (GET /newyorker/news). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object newyorkerNews() {
        return newyorkerNews(Map.of(), null);
    }

    /**
     * newyorker-sections (GET /newyorker/sections).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object newyorkerSections(Map<String, Object> params) {
        return newyorkerSections(params, null);
    }

    /**
     * newyorker-sections (GET /newyorker/sections). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object newyorkerSections(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("newyorker-sections", params);
        return client.request("newyorker-sections", params, options);
    }

    /**
     * newyorker-sections (GET /newyorker/sections). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object newyorkerSections() {
        return newyorkerSections(Map.of(), null);
    }

}
