package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "timesLive" operation group.
 * Reach it via {@code client.timesLive()}.
 */
public final class TimesLiveGroup {
    private final CrawloraClient client;

    public TimesLiveGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * timeslive-article (GET /timeslive/article).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object timesliveArticle(Map<String, Object> params) {
        return timesliveArticle(params, null);
    }

    /**
     * timeslive-article (GET /timeslive/article). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object timesliveArticle(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("timeslive-article", params);
        return client.request("timeslive-article", params, options);
    }

    /**
     * timeslive-headlines (GET /timeslive/headlines).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object timesliveHeadlines(Map<String, Object> params) {
        return timesliveHeadlines(params, null);
    }

    /**
     * timeslive-headlines (GET /timeslive/headlines). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object timesliveHeadlines(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("timeslive-headlines", params);
        return client.request("timeslive-headlines", params, options);
    }

    /**
     * timeslive-news (GET /timeslive/news).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object timesliveNews(Map<String, Object> params) {
        return timesliveNews(params, null);
    }

    /**
     * timeslive-news (GET /timeslive/news). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object timesliveNews(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("timeslive-news", params);
        return client.request("timeslive-news", params, options);
    }

    /**
     * timeslive-news (GET /timeslive/news). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object timesliveNews() {
        return timesliveNews(Map.of(), null);
    }

    /**
     * timeslive-sections (GET /timeslive/sections).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object timesliveSections(Map<String, Object> params) {
        return timesliveSections(params, null);
    }

    /**
     * timeslive-sections (GET /timeslive/sections). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object timesliveSections(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("timeslive-sections", params);
        return client.request("timeslive-sections", params, options);
    }

    /**
     * timeslive-sections (GET /timeslive/sections). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object timesliveSections() {
        return timesliveSections(Map.of(), null);
    }

}
