package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "whataburger" operation group.
 * Reach it via {@code client.whataburger()}.
 */
public final class WhataburgerGroup {
    private final CrawloraClient client;

    public WhataburgerGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * whataburger-sitemap (GET /whataburger/sitemap).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sitemap(Map<String, Object> params) {
        return sitemap(params, null);
    }

    /**
     * whataburger-sitemap (GET /whataburger/sitemap). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sitemap(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("whataburger-sitemap", params);
        return client.request("whataburger-sitemap", params, options);
    }

    /**
     * whataburger-sitemap (GET /whataburger/sitemap). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sitemap() {
        return sitemap(Map.of(), null);
    }

    /**
     * whataburger-store (GET /whataburger/store).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object store(Map<String, Object> params) {
        return store(params, null);
    }

    /**
     * whataburger-store (GET /whataburger/store). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object store(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("whataburger-store", params);
        return client.request("whataburger-store", params, options);
    }

}
