package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "wired" operation group.
 * Reach it via {@code client.wired()}.
 */
public final class WiredGroup {
    private final CrawloraClient client;

    public WiredGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * wired-article (GET /wired/article).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object article(Map<String, Object> params) {
        return article(params, null);
    }

    /**
     * wired-article (GET /wired/article). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object article(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("wired-article", params);
        return client.request("wired-article", params, options);
    }

    /**
     * wired-author (GET /wired/author).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object author(Map<String, Object> params) {
        return author(params, null);
    }

    /**
     * wired-author (GET /wired/author). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object author(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("wired-author", params);
        return client.request("wired-author", params, options);
    }

    /**
     * wired-headlines (GET /wired/headlines).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object headlines(Map<String, Object> params) {
        return headlines(params, null);
    }

    /**
     * wired-headlines (GET /wired/headlines). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object headlines(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("wired-headlines", params);
        return client.request("wired-headlines", params, options);
    }

    /**
     * wired-news (GET /wired/news).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object news(Map<String, Object> params) {
        return news(params, null);
    }

    /**
     * wired-news (GET /wired/news). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object news(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("wired-news", params);
        return client.request("wired-news", params, options);
    }

    /**
     * wired-news (GET /wired/news). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object news() {
        return news(Map.of(), null);
    }

    /**
     * wired-sections (GET /wired/sections).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sections(Map<String, Object> params) {
        return sections(params, null);
    }

    /**
     * wired-sections (GET /wired/sections). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sections(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("wired-sections", params);
        return client.request("wired-sections", params, options);
    }

    /**
     * wired-sections (GET /wired/sections). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object sections() {
        return sections(Map.of(), null);
    }

}
