package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "x" operation group.
 * Reach it via {@code client.x()}.
 */
public final class XGroup {
    private final CrawloraClient client;

    public XGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * x-post (GET /x/post/{id}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object post(Map<String, Object> params) {
        return post(params, null);
    }

    /**
     * x-post (GET /x/post/{id}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object post(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("x-post", params);
        return client.request("x-post", params, options);
    }

    /**
     * x-profile (GET /x/profile/{username}).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object profile(Map<String, Object> params) {
        return profile(params, null);
    }

    /**
     * x-profile (GET /x/profile/{username}). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object profile(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("x-profile", params);
        return client.request("x-profile", params, options);
    }

    /**
     * x-profile-posts (GET /x/profile/{username}/posts).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object profilePosts(Map<String, Object> params) {
        return profilePosts(params, null);
    }

    /**
     * x-profile-posts (GET /x/profile/{username}/posts). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object profilePosts(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("x-profile-posts", params);
        return client.request("x-profile-posts", params, options);
    }

}
