package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "yahooEntertainment" operation group.
 * Reach it via {@code client.yahooEntertainment()}.
 */
public final class YahooEntertainmentGroup {
    private final CrawloraClient client;

    public YahooEntertainmentGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * yahoo-entertainment-article (GET /yahoo-entertainment/article).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object article(Map<String, Object> params) {
        return article(params, null);
    }

    /**
     * yahoo-entertainment-article (GET /yahoo-entertainment/article). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object article(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("yahoo-entertainment-article", params);
        return client.request("yahoo-entertainment-article", params, options);
    }

    /**
     * yahoo-entertainment-category (GET /yahoo-entertainment/category).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object category(Map<String, Object> params) {
        return category(params, null);
    }

    /**
     * yahoo-entertainment-category (GET /yahoo-entertainment/category). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object category(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("yahoo-entertainment-category", params);
        return client.request("yahoo-entertainment-category", params, options);
    }

    /**
     * yahoo-entertainment-home (GET /yahoo-entertainment/home).
     *
     * @param params operation parameters
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object home(Map<String, Object> params) {
        return home(params, null);
    }

    /**
     * yahoo-entertainment-home (GET /yahoo-entertainment/home). with explicit request options.
     *
     * @param params operation parameters
     * @param options per-request options, or {@code null} for defaults
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object home(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("yahoo-entertainment-home", params);
        return client.request("yahoo-entertainment-home", params, options);
    }

    /**
     * yahoo-entertainment-home (GET /yahoo-entertainment/home). with no parameters.
     *
     * @return the parsed JSON response (Map/List/String/Number/Boolean), or an InputStream in stream mode
     */
    public Object home() {
        return home(Map.of(), null);
    }

}
