package net.crawlora.groups;

// Generated by scripts/generate.py. Do not edit manually.

import java.util.Map;
import net.crawlora.CrawloraClient;
import net.crawlora.OperationGroup;
import net.crawlora.RequestOptions;

/**
 * Generated typed accessor for the "youtube" operation group.
 * Reach it via {@code client.youtube()}.
 */
public final class YoutubeGroup {
    private final CrawloraClient client;

    public YoutubeGroup(CrawloraClient client) {
        this.client = client;
    }

    /**
     * youtube-captions (GET /youtube/captions/{id}).
     *
     * @param params operation parameters
     * @return the parsed response
     */
    public Object captions(Map<String, Object> params) {
        return captions(params, null);
    }

    /** youtube-captions with explicit {@link RequestOptions}. */
    public Object captions(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("youtube-captions", params);
        return client.request("youtube-captions", params, options);
    }

    /**
     * youtube-channel-playlists (GET /youtube/channel/{id}/playlists).
     *
     * @param params operation parameters
     * @return the parsed response
     */
    public Object channelPlaylists(Map<String, Object> params) {
        return channelPlaylists(params, null);
    }

    /** youtube-channel-playlists with explicit {@link RequestOptions}. */
    public Object channelPlaylists(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("youtube-channel-playlists", params);
        return client.request("youtube-channel-playlists", params, options);
    }

    /**
     * youtube-channel-search (GET /youtube/channel/{id}/search).
     *
     * @param params operation parameters
     * @return the parsed response
     */
    public Object channelSearch(Map<String, Object> params) {
        return channelSearch(params, null);
    }

    /** youtube-channel-search with explicit {@link RequestOptions}. */
    public Object channelSearch(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("youtube-channel-search", params);
        return client.request("youtube-channel-search", params, options);
    }

    /**
     * youtube-channel-shorts (GET /youtube/channel/{id}/shorts).
     *
     * @param params operation parameters
     * @return the parsed response
     */
    public Object channelShorts(Map<String, Object> params) {
        return channelShorts(params, null);
    }

    /** youtube-channel-shorts with explicit {@link RequestOptions}. */
    public Object channelShorts(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("youtube-channel-shorts", params);
        return client.request("youtube-channel-shorts", params, options);
    }

    /**
     * youtube-channel-videos (GET /youtube/channel/{id}/videos).
     *
     * @param params operation parameters
     * @return the parsed response
     */
    public Object channelVideos(Map<String, Object> params) {
        return channelVideos(params, null);
    }

    /** youtube-channel-videos with explicit {@link RequestOptions}. */
    public Object channelVideos(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("youtube-channel-videos", params);
        return client.request("youtube-channel-videos", params, options);
    }

    /**
     * youtube-comments (GET /youtube/comments/{id}).
     *
     * @param params operation parameters
     * @return the parsed response
     */
    public Object comments(Map<String, Object> params) {
        return comments(params, null);
    }

    /** youtube-comments with explicit {@link RequestOptions}. */
    public Object comments(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("youtube-comments", params);
        return client.request("youtube-comments", params, options);
    }

    /**
     * youtube-playlist (GET /youtube/playlist/{id}).
     *
     * @param params operation parameters
     * @return the parsed response
     */
    public Object playlist(Map<String, Object> params) {
        return playlist(params, null);
    }

    /** youtube-playlist with explicit {@link RequestOptions}. */
    public Object playlist(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("youtube-playlist", params);
        return client.request("youtube-playlist", params, options);
    }

    /**
     * youtube-profile (GET /youtube/profile/{id}).
     *
     * @param params operation parameters
     * @return the parsed response
     */
    public Object profile(Map<String, Object> params) {
        return profile(params, null);
    }

    /** youtube-profile with explicit {@link RequestOptions}. */
    public Object profile(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("youtube-profile", params);
        return client.request("youtube-profile", params, options);
    }

    /**
     * youtube-search (GET /youtube/search).
     *
     * @param params operation parameters
     * @return the parsed response
     */
    public Object search(Map<String, Object> params) {
        return search(params, null);
    }

    /** youtube-search with explicit {@link RequestOptions}. */
    public Object search(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("youtube-search", params);
        return client.request("youtube-search", params, options);
    }

    /** youtube-search with no parameters. */
    public Object search() {
        return search(Map.of(), null);
    }

    /**
     * youtube-tag (GET /youtube/tag/{tag}).
     *
     * @param params operation parameters
     * @return the parsed response
     */
    public Object tag(Map<String, Object> params) {
        return tag(params, null);
    }

    /** youtube-tag with explicit {@link RequestOptions}. */
    public Object tag(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("youtube-tag", params);
        return client.request("youtube-tag", params, options);
    }

    /**
     * youtube-transcript (GET /youtube/transcript/{id}).
     * Supports text response mode.
     *
     * @param params operation parameters
     * @return the parsed response
     */
    public Object transcript(Map<String, Object> params) {
        return transcript(params, null);
    }

    /** youtube-transcript with explicit {@link RequestOptions}. */
    public Object transcript(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("youtube-transcript", params);
        return client.request("youtube-transcript", params, options);
    }

    /**
     * youtube-transcript-languages (GET /youtube/transcript/{id}/languages).
     *
     * @param params operation parameters
     * @return the parsed response
     */
    public Object transcriptLanguages(Map<String, Object> params) {
        return transcriptLanguages(params, null);
    }

    /** youtube-transcript-languages with explicit {@link RequestOptions}. */
    public Object transcriptLanguages(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("youtube-transcript-languages", params);
        return client.request("youtube-transcript-languages", params, options);
    }

    /**
     * youtube-video (GET /youtube/video/{id}).
     *
     * @param params operation parameters
     * @return the parsed response
     */
    public Object video(Map<String, Object> params) {
        return video(params, null);
    }

    /** youtube-video with explicit {@link RequestOptions}. */
    public Object video(Map<String, Object> params, RequestOptions options) {
        OperationGroup.checkParams("youtube-video", params);
        return client.request("youtube-video", params, options);
    }

}
