package net.crawlora;

// Generated by scripts/generate.py. Do not edit manually.

import net.crawlora.groups.*;

/**
 * Generated base class providing {@link CrawloraClient} a typed accessor for
 * every operation group, e.g. {@code client.bing().search(params)} or
 * {@code client.google().search(params)}.
 */
public abstract class ClientGroups {
    /**
     * Typed accessor for the "agoda" operation group.
     * @return a new {@link AgodaGroup} bound to this client
     */
    public AgodaGroup agoda() {
        return new AgodaGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "airbnb" operation group.
     * @return a new {@link AirbnbGroup} bound to this client
     */
    public AirbnbGroup airbnb() {
        return new AirbnbGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "amazonJobs" operation group.
     * @return a new {@link AmazonJobsGroup} bound to this client
     */
    public AmazonJobsGroup amazonJobs() {
        return new AmazonJobsGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "amazon" operation group.
     * @return a new {@link AmazonGroup} bound to this client
     */
    public AmazonGroup amazon() {
        return new AmazonGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "anime" operation group.
     * @return a new {@link AnimeGroup} bound to this client
     */
    public AnimeGroup anime() {
        return new AnimeGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "appleBooks" operation group.
     * @return a new {@link AppleBooksGroup} bound to this client
     */
    public AppleBooksGroup appleBooks() {
        return new AppleBooksGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "appleJobs" operation group.
     * @return a new {@link AppleJobsGroup} bound to this client
     */
    public AppleJobsGroup appleJobs() {
        return new AppleJobsGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "applePodcasts" operation group.
     * @return a new {@link ApplePodcastsGroup} bound to this client
     */
    public ApplePodcastsGroup applePodcasts() {
        return new ApplePodcastsGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "appStore" operation group.
     * @return a new {@link AppStoreGroup} bound to this client
     */
    public AppStoreGroup appStore() {
        return new AppStoreGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "autotrader" operation group.
     * @return a new {@link AutotraderGroup} bound to this client
     */
    public AutotraderGroup autotrader() {
        return new AutotraderGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "bestBuy" operation group.
     * @return a new {@link BestBuyGroup} bound to this client
     */
    public BestBuyGroup bestBuy() {
        return new BestBuyGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "billing" operation group.
     * @return a new {@link BillingGroup} bound to this client
     */
    public BillingGroup billing() {
        return new BillingGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "bing" operation group.
     * @return a new {@link BingGroup} bound to this client
     */
    public BingGroup bing() {
        return new BingGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "bluesky" operation group.
     * @return a new {@link BlueskyGroup} bound to this client
     */
    public BlueskyGroup bluesky() {
        return new BlueskyGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "booking" operation group.
     * @return a new {@link BookingGroup} bound to this client
     */
    public BookingGroup booking() {
        return new BookingGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "boxOfficeMojo" operation group.
     * @return a new {@link BoxOfficeMojoGroup} bound to this client
     */
    public BoxOfficeMojoGroup boxOfficeMojo() {
        return new BoxOfficeMojoGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "brand" operation group.
     * @return a new {@link BrandGroup} bound to this client
     */
    public BrandGroup brand() {
        return new BrandGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "brave" operation group.
     * @return a new {@link BraveGroup} bound to this client
     */
    public BraveGroup brave() {
        return new BraveGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "capterra" operation group.
     * @return a new {@link CapterraGroup} bound to this client
     */
    public CapterraGroup capterra() {
        return new CapterraGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "carMax" operation group.
     * @return a new {@link CarMaxGroup} bound to this client
     */
    public CarMaxGroup carMax() {
        return new CarMaxGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "carsCom" operation group.
     * @return a new {@link CarsComGroup} bound to this client
     */
    public CarsComGroup carsCom() {
        return new CarsComGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "chromeWebStore" operation group.
     * @return a new {@link ChromeWebStoreGroup} bound to this client
     */
    public ChromeWebStoreGroup chromeWebStore() {
        return new ChromeWebStoreGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "coinGecko" operation group.
     * @return a new {@link CoinGeckoGroup} bound to this client
     */
    public CoinGeckoGroup coinGecko() {
        return new CoinGeckoGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "congress" operation group.
     * @return a new {@link CongressGroup} bound to this client
     */
    public CongressGroup congress() {
        return new CongressGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "web" operation group.
     * @return a new {@link WebGroup} bound to this client
     */
    public WebGroup web() {
        return new WebGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "costco" operation group.
     * @return a new {@link CostcoGroup} bound to this client
     */
    public CostcoGroup costco() {
        return new CostcoGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "datasets" operation group.
     * @return a new {@link DatasetsGroup} bound to this client
     */
    public DatasetsGroup datasets() {
        return new DatasetsGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "depop" operation group.
     * @return a new {@link DepopGroup} bound to this client
     */
    public DepopGroup depop() {
        return new DepopGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "discogs" operation group.
     * @return a new {@link DiscogsGroup} bound to this client
     */
    public DiscogsGroup discogs() {
        return new DiscogsGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "doorDash" operation group.
     * @return a new {@link DoorDashGroup} bound to this client
     */
    public DoorDashGroup doorDash() {
        return new DoorDashGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "draftKingsSportsbook" operation group.
     * @return a new {@link DraftKingsSportsbookGroup} bound to this client
     */
    public DraftKingsSportsbookGroup draftKingsSportsbook() {
        return new DraftKingsSportsbookGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "duckDuckGoSearch" operation group.
     * @return a new {@link DuckDuckGoSearchGroup} bound to this client
     */
    public DuckDuckGoSearchGroup duckDuckGoSearch() {
        return new DuckDuckGoSearchGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "eBay" operation group.
     * @return a new {@link EBayGroup} bound to this client
     */
    public EBayGroup eBay() {
        return new EBayGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "espn" operation group.
     * @return a new {@link EspnGroup} bound to this client
     */
    public EspnGroup espn() {
        return new EspnGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "etsy" operation group.
     * @return a new {@link EtsyGroup} bound to this client
     */
    public EtsyGroup etsy() {
        return new EtsyGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "expedia" operation group.
     * @return a new {@link ExpediaGroup} bound to this client
     */
    public ExpediaGroup expedia() {
        return new ExpediaGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "facebook" operation group.
     * @return a new {@link FacebookGroup} bound to this client
     */
    public FacebookGroup facebook() {
        return new FacebookGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "fiverr" operation group.
     * @return a new {@link FiverrGroup} bound to this client
     */
    public FiverrGroup fiverr() {
        return new FiverrGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "geocoding" operation group.
     * @return a new {@link GeocodingGroup} bound to this client
     */
    public GeocodingGroup geocoding() {
        return new GeocodingGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "gitHub" operation group.
     * @return a new {@link GitHubGroup} bound to this client
     */
    public GitHubGroup gitHub() {
        return new GitHubGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "goodreads" operation group.
     * @return a new {@link GoodreadsGroup} bound to this client
     */
    public GoodreadsGroup goodreads() {
        return new GoodreadsGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "googleJobs" operation group.
     * @return a new {@link GoogleJobsGroup} bound to this client
     */
    public GoogleJobsGroup googleJobs() {
        return new GoogleJobsGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "google" operation group.
     * @return a new {@link GoogleGroup} bound to this client
     */
    public GoogleGroup google() {
        return new GoogleGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "googlePatents" operation group.
     * @return a new {@link GooglePatentsGroup} bound to this client
     */
    public GooglePatentsGroup googlePatents() {
        return new GooglePatentsGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "googlePlay" operation group.
     * @return a new {@link GooglePlayGroup} bound to this client
     */
    public GooglePlayGroup googlePlay() {
        return new GooglePlayGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "hM" operation group.
     * @return a new {@link HMGroup} bound to this client
     */
    public HMGroup hM() {
        return new HMGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "imdb" operation group.
     * @return a new {@link ImdbGroup} bound to this client
     */
    public ImdbGroup imdb() {
        return new ImdbGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "importYeti" operation group.
     * @return a new {@link ImportYetiGroup} bound to this client
     */
    public ImportYetiGroup importYeti() {
        return new ImportYetiGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "indeed" operation group.
     * @return a new {@link IndeedGroup} bound to this client
     */
    public IndeedGroup indeed() {
        return new IndeedGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "instacart" operation group.
     * @return a new {@link InstacartGroup} bound to this client
     */
    public InstacartGroup instacart() {
        return new InstacartGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "instagram" operation group.
     * @return a new {@link InstagramGroup} bound to this client
     */
    public InstagramGroup instagram() {
        return new InstagramGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "jobs" operation group.
     * @return a new {@link JobsGroup} bound to this client
     */
    public JobsGroup jobs() {
        return new JobsGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "justWatch" operation group.
     * @return a new {@link JustWatchGroup} bound to this client
     */
    public JustWatchGroup justWatch() {
        return new JustWatchGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "kalshi" operation group.
     * @return a new {@link KalshiGroup} bound to this client
     */
    public KalshiGroup kalshi() {
        return new KalshiGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "kohlS" operation group.
     * @return a new {@link KohlSGroup} bound to this client
     */
    public KohlSGroup kohlS() {
        return new KohlSGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "letterboxd" operation group.
     * @return a new {@link LetterboxdGroup} bound to this client
     */
    public LetterboxdGroup letterboxd() {
        return new LetterboxdGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "linkedIn" operation group.
     * @return a new {@link LinkedInGroup} bound to this client
     */
    public LinkedInGroup linkedIn() {
        return new LinkedInGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "lululemon" operation group.
     * @return a new {@link LululemonGroup} bound to this client
     */
    public LululemonGroup lululemon() {
        return new LululemonGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "macyS" operation group.
     * @return a new {@link MacySGroup} bound to this client
     */
    public MacySGroup macyS() {
        return new MacySGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "manga" operation group.
     * @return a new {@link MangaGroup} bound to this client
     */
    public MangaGroup manga() {
        return new MangaGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "mercari" operation group.
     * @return a new {@link MercariGroup} bound to this client
     */
    public MercariGroup mercari() {
        return new MercariGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "metaJobs" operation group.
     * @return a new {@link MetaJobsGroup} bound to this client
     */
    public MetaJobsGroup metaJobs() {
        return new MetaJobsGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "metacritic" operation group.
     * @return a new {@link MetacriticGroup} bound to this client
     */
    public MetacriticGroup metacritic() {
        return new MetacriticGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "metaculus" operation group.
     * @return a new {@link MetaculusGroup} bound to this client
     */
    public MetaculusGroup metaculus() {
        return new MetaculusGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "mlb" operation group.
     * @return a new {@link MlbGroup} bound to this client
     */
    public MlbGroup mlb() {
        return new MlbGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "nike" operation group.
     * @return a new {@link NikeGroup} bound to this client
     */
    public NikeGroup nike() {
        return new NikeGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "numbeo" operation group.
     * @return a new {@link NumbeoGroup} bound to this client
     */
    public NumbeoGroup numbeo() {
        return new NumbeoGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "oldNavy" operation group.
     * @return a new {@link OldNavyGroup} bound to this client
     */
    public OldNavyGroup oldNavy() {
        return new OldNavyGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "openTable" operation group.
     * @return a new {@link OpenTableGroup} bound to this client
     */
    public OpenTableGroup openTable() {
        return new OpenTableGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "meta" operation group.
     * @return a new {@link MetaGroup} bound to this client
     */
    public MetaGroup meta() {
        return new MetaGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "pinterest" operation group.
     * @return a new {@link PinterestGroup} bound to this client
     */
    public PinterestGroup pinterest() {
        return new PinterestGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "pitchBook" operation group.
     * @return a new {@link PitchBookGroup} bound to this client
     */
    public PitchBookGroup pitchBook() {
        return new PitchBookGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "playStation" operation group.
     * @return a new {@link PlayStationGroup} bound to this client
     */
    public PlayStationGroup playStation() {
        return new PlayStationGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "polymarket" operation group.
     * @return a new {@link PolymarketGroup} bound to this client
     */
    public PolymarketGroup polymarket() {
        return new PolymarketGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "poshmark" operation group.
     * @return a new {@link PoshmarkGroup} bound to this client
     */
    public PoshmarkGroup poshmark() {
        return new PoshmarkGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "productHunt" operation group.
     * @return a new {@link ProductHuntGroup} bound to this client
     */
    public ProductHuntGroup productHunt() {
        return new ProductHuntGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "reddit" operation group.
     * @return a new {@link RedditGroup} bound to this client
     */
    public RedditGroup reddit() {
        return new RedditGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "redfin" operation group.
     * @return a new {@link RedfinGroup} bound to this client
     */
    public RedfinGroup redfin() {
        return new RedfinGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "referrals" operation group.
     * @return a new {@link ReferralsGroup} bound to this client
     */
    public ReferralsGroup referrals() {
        return new ReferralsGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "rottenTomatoes" operation group.
     * @return a new {@link RottenTomatoesGroup} bound to this client
     */
    public RottenTomatoesGroup rottenTomatoes() {
        return new RottenTomatoesGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "samSClub" operation group.
     * @return a new {@link SamSclubGroup} bound to this client
     */
    public SamSclubGroup samSClub() {
        return new SamSclubGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "secEdgar" operation group.
     * @return a new {@link SecEdgarGroup} bound to this client
     */
    public SecEdgarGroup secEdgar() {
        return new SecEdgarGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "sephora" operation group.
     * @return a new {@link SephoraGroup} bound to this client
     */
    public SephoraGroup sephora() {
        return new SephoraGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "shopApp" operation group.
     * @return a new {@link ShopAppGroup} bound to this client
     */
    public ShopAppGroup shopApp() {
        return new ShopAppGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "shopify" operation group.
     * @return a new {@link ShopifyGroup} bound to this client
     */
    public ShopifyGroup shopify() {
        return new ShopifyGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "similarWeb" operation group.
     * @return a new {@link SimilarWebGroup} bound to this client
     */
    public SimilarWebGroup similarWeb() {
        return new SimilarWebGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "sofaScore" operation group.
     * @return a new {@link SofaScoreGroup} bound to this client
     */
    public SofaScoreGroup sofaScore() {
        return new SofaScoreGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "soundCloud" operation group.
     * @return a new {@link SoundCloudGroup} bound to this client
     */
    public SoundCloudGroup soundCloud() {
        return new SoundCloudGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "spotifyPodcasts" operation group.
     * @return a new {@link SpotifyPodcastsGroup} bound to this client
     */
    public SpotifyPodcastsGroup spotifyPodcasts() {
        return new SpotifyPodcastsGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "spotify" operation group.
     * @return a new {@link SpotifyGroup} bound to this client
     */
    public SpotifyGroup spotify() {
        return new SpotifyGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "steam" operation group.
     * @return a new {@link SteamGroup} bound to this client
     */
    public SteamGroup steam() {
        return new SteamGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "stockX" operation group.
     * @return a new {@link StockXGroup} bound to this client
     */
    public StockXGroup stockX() {
        return new StockXGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "strava" operation group.
     * @return a new {@link StravaGroup} bound to this client
     */
    public StravaGroup strava() {
        return new StravaGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "target" operation group.
     * @return a new {@link TargetGroup} bound to this client
     */
    public TargetGroup target() {
        return new TargetGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "teslaJobs" operation group.
     * @return a new {@link TeslaJobsGroup} bound to this client
     */
    public TeslaJobsGroup teslaJobs() {
        return new TeslaJobsGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "threads" operation group.
     * @return a new {@link ThreadsGroup} bound to this client
     */
    public ThreadsGroup threads() {
        return new ThreadsGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "ticketmaster" operation group.
     * @return a new {@link TicketmasterGroup} bound to this client
     */
    public TicketmasterGroup ticketmaster() {
        return new TicketmasterGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "tiktok" operation group.
     * @return a new {@link TiktokGroup} bound to this client
     */
    public TiktokGroup tiktok() {
        return new TiktokGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "tmdb" operation group.
     * @return a new {@link TmdbGroup} bound to this client
     */
    public TmdbGroup tmdb() {
        return new TmdbGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "tripAdvisor" operation group.
     * @return a new {@link TripAdvisorGroup} bound to this client
     */
    public TripAdvisorGroup tripAdvisor() {
        return new TripAdvisorGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "tripCom" operation group.
     * @return a new {@link TripComGroup} bound to this client
     */
    public TripComGroup tripCom() {
        return new TripComGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "trustMrr" operation group.
     * @return a new {@link TrustMrrGroup} bound to this client
     */
    public TrustMrrGroup trustMrr() {
        return new TrustMrrGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "trustpilot" operation group.
     * @return a new {@link TrustpilotGroup} bound to this client
     */
    public TrustpilotGroup trustpilot() {
        return new TrustpilotGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "twitch" operation group.
     * @return a new {@link TwitchGroup} bound to this client
     */
    public TwitchGroup twitch() {
        return new TwitchGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "uberEats" operation group.
     * @return a new {@link UberEatsGroup} bound to this client
     */
    public UberEatsGroup uberEats() {
        return new UberEatsGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "ultaBeauty" operation group.
     * @return a new {@link UltaBeautyGroup} bound to this client
     */
    public UltaBeautyGroup ultaBeauty() {
        return new UltaBeautyGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "upwork" operation group.
     * @return a new {@link UpworkGroup} bound to this client
     */
    public UpworkGroup upwork() {
        return new UpworkGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "usage" operation group.
     * @return a new {@link UsageGroup} bound to this client
     */
    public UsageGroup usage() {
        return new UsageGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "user" operation group.
     * @return a new {@link UserGroup} bound to this client
     */
    public UserGroup user() {
        return new UserGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "accountDeletion" operation group.
     * @return a new {@link AccountDeletionGroup} bound to this client
     */
    public AccountDeletionGroup accountDeletion() {
        return new AccountDeletionGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "usptoPatentPublicSearch" operation group.
     * @return a new {@link UsptoPatentPublicSearchGroup} bound to this client
     */
    public UsptoPatentPublicSearchGroup usptoPatentPublicSearch() {
        return new UsptoPatentPublicSearchGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "vinted" operation group.
     * @return a new {@link VintedGroup} bound to this client
     */
    public VintedGroup vinted() {
        return new VintedGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "walmart" operation group.
     * @return a new {@link WalmartGroup} bound to this client
     */
    public WalmartGroup walmart() {
        return new WalmartGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "wayfair" operation group.
     * @return a new {@link WayfairGroup} bound to this client
     */
    public WayfairGroup wayfair() {
        return new WayfairGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "whatnot" operation group.
     * @return a new {@link WhatnotGroup} bound to this client
     */
    public WhatnotGroup whatnot() {
        return new WhatnotGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "wish" operation group.
     * @return a new {@link WishGroup} bound to this client
     */
    public WishGroup wish() {
        return new WishGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "x" operation group.
     * @return a new {@link XGroup} bound to this client
     */
    public XGroup x() {
        return new XGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "yahooAutos" operation group.
     * @return a new {@link YahooAutosGroup} bound to this client
     */
    public YahooAutosGroup yahooAutos() {
        return new YahooAutosGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "yahooEntertainment" operation group.
     * @return a new {@link YahooEntertainmentGroup} bound to this client
     */
    public YahooEntertainmentGroup yahooEntertainment() {
        return new YahooEntertainmentGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "yahooFinance" operation group.
     * @return a new {@link YahooFinanceGroup} bound to this client
     */
    public YahooFinanceGroup yahooFinance() {
        return new YahooFinanceGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "yahooHealth" operation group.
     * @return a new {@link YahooHealthGroup} bound to this client
     */
    public YahooHealthGroup yahooHealth() {
        return new YahooHealthGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "yahooLife" operation group.
     * @return a new {@link YahooLifeGroup} bound to this client
     */
    public YahooLifeGroup yahooLife() {
        return new YahooLifeGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "yahooNews" operation group.
     * @return a new {@link YahooNewsGroup} bound to this client
     */
    public YahooNewsGroup yahooNews() {
        return new YahooNewsGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "yahooSearch" operation group.
     * @return a new {@link YahooSearchGroup} bound to this client
     */
    public YahooSearchGroup yahooSearch() {
        return new YahooSearchGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "yahooShopping" operation group.
     * @return a new {@link YahooShoppingGroup} bound to this client
     */
    public YahooShoppingGroup yahooShopping() {
        return new YahooShoppingGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "yahooSports" operation group.
     * @return a new {@link YahooSportsGroup} bound to this client
     */
    public YahooSportsGroup yahooSports() {
        return new YahooSportsGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "yahooTech" operation group.
     * @return a new {@link YahooTechGroup} bound to this client
     */
    public YahooTechGroup yahooTech() {
        return new YahooTechGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "yelp" operation group.
     * @return a new {@link YelpGroup} bound to this client
     */
    public YelpGroup yelp() {
        return new YelpGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "youtube" operation group.
     * @return a new {@link YoutubeGroup} bound to this client
     */
    public YoutubeGroup youtube() {
        return new YoutubeGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "zalando" operation group.
     * @return a new {@link ZalandoGroup} bound to this client
     */
    public ZalandoGroup zalando() {
        return new ZalandoGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "zappos" operation group.
     * @return a new {@link ZapposGroup} bound to this client
     */
    public ZapposGroup zappos() {
        return new ZapposGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "zara" operation group.
     * @return a new {@link ZaraGroup} bound to this client
     */
    public ZaraGroup zara() {
        return new ZaraGroup((CrawloraClient) this);
    }

    /**
     * Typed accessor for the "zillow" operation group.
     * @return a new {@link ZillowGroup} bound to this client
     */
    public ZillowGroup zillow() {
        return new ZillowGroup((CrawloraClient) this);
    }

}
